### PR TITLE
Fix crash caused by moving ground_plane

### LINKED ISSUE #2605: Crash after calling set_pose service, with Assertion `math::verifyTransform(mT)' failed
## Environment
* OS Version: Ubuntu 24.04
* Source or binary build?
    source build
    gz-sim9 version: c1f379ee7fac10a5118df672cdb0e391605bd0f5
    built with 
    gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4)
    build options: -DCMAKE_BUILD_TYPE=Coverage
    also reproduced on gz-sim8 version: e237d591d853aad7c95d7f333d65d2412ba4e7f0

## Description
* Expected behavior: Gazebo doesn't crash
* Actual behavior: Gazebo crashes

## Steps to reproduce
1. gz sim [a.txt](https://github.com/user-attachments/files/16922238/a.txt) -r &
2. call /world/default/set_pose service, with

```bash
gz service --timeout 10000 -s /world/default/set_pose --reptype gz.msgs.Boolean --reqtype gz.msgs.Pose --req 'name: "ground_plane"
position {
  x: -1.135452379765546
  y: 1.5092107430792936
  z: 8.13648902952947
}'
```

## Output
The output is similar as #2538, with different assertion failure location (FreeJoint.cpp:670)

```
gz sim server: ./dart/dynamics/RevoluteJoint.cpp:186: virtual void dart::dynamics::RevoluteJoint::updateRelativeTransform() const: Assertion `math::verifyTransform(mT)' failed.
Stack trace (most recent call last):
#31   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x78755f0545db, in 
#30   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x78755f0500fe, in 
#29   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x78755f04d8ef, in 
#28   Object "/usr/lib/x86_64-linux-gnu/ruby/3.2.0/fiddle.so", at 0x78755ec27b13, in 
#27   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x78755f0163bb, in rb_nogvl
#26   Object "/usr/lib/x86_64-linux-gnu/ruby/3.2.0/fiddle.so", at 0x78755ec2743b, in 
#25   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x78755ecfa0bd, in ffi_call
#24   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x78755ecf73ee, in 
#23   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x78755ecfab15, in 
#22   Object "/data/play/robot/workspace/install/lib/libgz-sim9-gz.so.9.0.0~pre1", at 0x7875586bdc83, in runServer
#21   Object "/data/play/robot/workspace/install/lib/libgz-sim9.so.9", at 0x787556fe1707, in gz::sim::v9::Server::Run(bool, unsigned long, bool)
#20   Object "/data/play/robot/workspace/install/lib/libgz-sim9.so.9", at 0x787557051bda, in 
#19   Object "/data/play/robot/workspace/install/lib/libgz-sim9.so.9", at 0x7875570835f3, in gz::sim::v9::SimulationRunner::Run(unsigned long)
#18   Object "/data/play/robot/workspace/install/lib/libgz-sim9.so.9", at 0x7875570845f8, in gz::sim::v9::SimulationRunner::Step(gz::sim::v9::UpdateInfo const&)
#17   Object "/data/play/robot/workspace/install/lib/libgz-sim9.so.9", at 0x787557080ab4, in gz::sim::v9::SimulationRunner::UpdateSystems()
#16   Object "/data/play/robot/workspace/install/lib/gz-sim-9/plugins/libgz-sim-physics-system.so", at 0x78752ab27f33, in 
#15   Object "/data/play/robot/workspace/install/lib/gz-sim-9/plugins/libgz-sim-physics-system.so", at 0x78752ab4720b, in 
#14   Object "/data/play/robot/workspace/install/lib/gz-sim-9/plugins/libgz-sim-physics-system.so", at 0x78752ac07414, in 
#13   Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255de7c8, in 
#12   Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255e69e5, in 
#11   Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255ea19e, in 
#10   Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255eeead, in 
#9    Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255f3030, in 
#8    Object "/data/play/robot/workspace/install/lib/gz-physics-8/engine-plugins/libgz-physics-dartsim-plugin.so", at 0x7875255dec1d, in 
#7    Object "/lib/x86_64-linux-gnu/libdart.so.6.13", at 0x78752483cbd2, in dart::dynamics::Frame::getWorldTransform() const
#6    Object "/lib/x86_64-linux-gnu/libdart.so.6.13", at 0x787524888821, in dart::dynamics::Joint::getRelativeTransform() const
#5    Object "/lib/x86_64-linux-gnu/libdart.so.6.13", at 0x7875248e0725, in dart::dynamics::RevoluteJoint::updateRelativeTransform() const
#4    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x78755ea3b506, in __assert_fail
#3    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x78755ea2881a, in 
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x78755ea288fe, in abort
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x78755ea4526d, in gsignal
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x78755ea9eb1c, in pthread_kill
Aborted (Signal sent by tkill() 599683 1000)
```

### PR DESCRIPTION
**Pull request by XINJIANGMO**
# 🦟 Bug fix

Fixes #2605 

## Summary
This crash occurs due to an attempt to move the groud_plane, and according to @azeey commented on this [issue](https://github.com/gazebosim/gz-sim/issues/2605), we need to detect if the moving object is ground_plane, and if so, prohibit it.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

File: src/systems/physics/Physics.cc [hunk 1]
```diff
@@ -2448,7 +2448,15 @@ void PhysicsPrivate::UpdatePhysics(EntityComponentManager &_ecm)
                  << std::endl;
           return true;
         }
-
+        // Check if the model is ground_plane
+        // If so, we refuse to set the pose
+        auto nameComp = _ecm.Component<components::Name>(_entity);
+        if ((nameComp && nameComp->Data() == "ground_plane"))
```
Comment (iche033) [inline src/systems/physics/Physics.cc]: I think the issue is with plane collision geometries and not just the `ground_plane`? If so, can we change this to check whether or not model contains any plane collision geometry instead?

Comment (XINJIANGMO) [reply src/systems/physics/Physics.cc]: That's a good point! You are right! If I change  `ground_plane` to another name , it also crashes. So it is a good idea to check whether or not model contains any plane collision geometry to fix it.
I will fix it.

File: src/systems/physics/Physics.cc [hunk 2]
```diff
@@ -3127,6 +3142,26 @@ std::map<Entity, physics::FrameData3d> PhysicsPrivate::ChangedLinks(
   return linkFrameData;
 }
 
+//////////////////////////////////////////////////
+bool PhysicsPrivate::ModelContainsPlaneCollision(const Entity &modelEntity,
+    EntityComponentManager &_ecm) const
+{
+  sim::Model model(modelEntity);
```
Comment (iche033) [inline src/systems/physics/Physics.cc]: minor style nit:

```suggestion
bool PhysicsPrivate::ModelContainsPlaneCollision(const Entity &_modelEntity,
    EntityComponentManager &_ecm) const
{
  sim::Model model(_modelEntity);
```

File: src/systems/physics/Physics.cc [hunk 3]
```diff
@@ -281,6 +281,13 @@ class gz::sim::systems::PhysicsPrivate
               EntityComponentManager &_ecm,
               const gz::physics::ForwardStep::Output &_updatedLinks);
 
+  /// \brief Check if a model contains any plane collision geometry.
+  /// \param[in] modelEntity The entity of the model to check.
+  /// \param[in] _ecm The entity component manager.
+  /// \return True if any collision geometry is a plane.
+  public: bool ModelContainsPlaneCollision(const Entity &modelEntity,
```
Comment (iche033) [inline src/systems/physics/Physics.cc]: minor style nit:

```suggestion
  public: bool ModelContainsPlaneCollision(const Entity &_modelEntity,
```

**Review by iche033 — COMMENTED** [review]
looks good, just one minor style suggestion
