### PR TITLE
Print an error message when trying to load SDF files that don't contain a `<world>`

### LINKED ISSUE #1941: [BUG] gazebo citadel fails to load sdf files that aren't a part of a <world> but doesn't throw an error.
## Environment
* OS Version: Ubuntu 20.04
binary build
Citadel v3.14.0

## Description
* Expected behavior: gazebo throws an error to state that sdfs must be part of a world to be loaded, then closes
* Actual behavior: gazebo says that it load the file, then gazebo terminates it self with no error.

## Steps to reproduce

- generate an sdf from with the urdf -> sdf converter tool via `ign sdf -p"
- attempt the load the sdf via `ign gazebo -v4 <path_to_sdf>

## Output
```
[Msg] Ignition Gazebo GUI    v3.14.0
[Dbg] [ign.cc:160] Subscribing to [/gazebo/starting_world].
[Dbg] [ign.cc:162] Waiting for a world to be set from the GUI...
[Dbg] [Gui.cc:245] Waiting for subscribers to [/gazebo/starting_world]...
[Msg] Received world [<path_to_sdf>/diff_bot.sdf] from the GUI.
[Dbg] [ign.cc:166] Unsubscribing from [/gazebo/starting_world].
[Msg] Ignition Gazebo Server v3.14.0
[Msg] Loading SDF world file[<path_to_sdf>diff_bot.sdf].
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[Dbg] [ign.cc:410] Shutting down ign-gazebo-server
```

### PR DESCRIPTION
**Pull request by Henrique-BO**
# 🦟 Bug fix

Fixes #1941

## Summary

Added an error message when attempting to load an SDF file that doesn't contain a world.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: src/Server_TEST.cc [hunk 1]
```diff
@@ -1088,6 +1088,41 @@ TEST_P(ServerFixture, AddResourcePaths)
...
+  // Initialize logging
+  std::string logBasePath = common::joinPaths(PROJECT_BINARY_PATH, "tmp");
+  common::setenv(IGN_HOMEDIR, logBasePath);
+  std::string path = common::uuid();
+  ignLogInit(path, "test.log");
+
+  // Start server with model SDF file
+  ServerConfig serverConfig;
+  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
+      "/test/worlds/models/sphere/model.sdf");
```
Comment (ahcorde) [inline src/Server_TEST.cc:1103]: use `common::joinPaths`

File: src/Server_TEST.cc [hunk 2]
```diff
@@ -1088,6 +1088,41 @@ TEST_P(ServerFixture, AddResourcePaths)
...
+  }
+  EXPECT_TRUE(errFound);
+
+  // Stop logging
+  ignLogClose();
+  common::removeAll(logBasePath);
+}
+
+
 // Run multiple times. We want to make sure that static globals don't cause
```
Comment (ahcorde) [inline src/Server_TEST.cc:1126]:
```suggestion
}

// Run multiple times. We want to make sure that static globals don't cause
```

**Review by ahcorde — CHANGES_REQUESTED** [review]

File: src/Server_TEST.cc (hunk 1 above)
Comment (Henrique-BO) [reply src/Server_TEST.cc]: Done in [9059a2b](https://github.com/gazebosim/gz-sim/pull/1998/commits/9059a2b3073f4de18920775245ed66dba432a62b).

File: src/Server_TEST.cc (hunk 2 above)
Comment (Henrique-BO) [reply src/Server_TEST.cc]: Done in [9059a2b](https://github.com/gazebosim/gz-sim/pull/1998/commits/9059a2b3073f4de18920775245ed66dba432a62b).

File: src/Server.cc [hunk 3]
```diff
@@ -182,6 +182,12 @@ Server::Server(const ServerConfig &_config)
     return;
   }
 
+  if (this->dataPtr->sdfRoot.WorldCount() == 0)
+  {
+    ignerr << "SDF file doesn't contain a world.\n";
```
Comment (azeey) [inline src/Server.cc:187]: It would be helpful to add that if the user wants to spawn a model, they could use the ResourceSpawner GUI plugin or the `world/<world name/create` service.

Comment (Henrique-BO) [reply src/Server.cc]: Done in bee3130.

**Review by azeey — APPROVED** [review]

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
Note, this should not be forward ported to gz-sim7 because loading model files directly is supported in that branch.
