### PR TITLE
Fix component updates

### LINKED ISSUE #1022: Modifying lights in component inspector not working
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
  
Source, `main` branch, commit 1fb320715525a86361f2710ffa6aadb4c56a58c0

## Description
* Expected behavior: Lights to change color when using the component inspector
* Actual behavior: Most of the time nothing happens (sometimes will change color but only seems to be once). When changing one of the RGBA sliders then changing another, the first slider will reset back. For example, if I change R then B, R seems to reset back.

Peek 2021-09-10 16-08

## Steps to reproduce

1. Apply fix from https://github.com/ignitionrobotics/ign-gazebo/pull/1018
2. `ign gazebo -v 4 lights.sdf`
3. Attempt to change the color of any of the lights

### PR DESCRIPTION
**Pull request by jennuine**
# 🦟 Bug fix

Fixes #1022

## Summary

To speed up performance, removed components were cached/stored here: 
https://github.com/gazebosim/gz-sim/blob/1f6c1263fea66cd1736f420741acbe030a3f3089/include/ignition/gazebo/detail/View.hh#L140-L149

Then when the same component was re-added: https://github.com/gazebosim/gz-sim/blob/1f6c1263fea66cd1736f420741acbe030a3f3089/src/EntityComponentManager.cc#L1088-L1089

The component data was moved from `invalidData` to `validData` but the data was never updated.

The fix is to check that component needs updated in the `EntityComponentManager::SetState` functions then retrieve the component and deserialize the data again (to update the re-added component).

---

To run unit tests:
```bash
./path/to/build/UNIT_EntityComponentManager_TEST --gtest_filter="*AddRemoveAddComponents*"
```
---

To test through the GUI: 
```bash
ign gazebo -v 4 lights.sdf
```

**Before PR**
before_pr

**After PR**
after_pr

Thanks @chapulina for the help!

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: src/EntityComponentManager.cc [hunk 1]
```diff
@@ -493,7 +493,16 @@ Entity EntityComponentManager::CloneImpl(Entity _entity, Entity _parent,
...
 
-    this->CreateComponentImplementation(clonedEntity, type, clonedComp.get());
+    auto updateData =
+      this->CreateComponentImplementation(clonedEntity, type, clonedComp.get());
+    if (updateData)
+    {
+      // When a cloned entity is removed, it erases all components/data so a new
+      // cloned entity should not have components to be updated
+      ignerr << "The component's data needs to be updated but this is not "
+             << "expected. Please submit an issue including your use case "
```
Comment (ahcorde) [inline src/EntityComponentManager.cc:503]: What do you think about adding here the url the github repo ?

**Review by ahcorde — CHANGES_REQUESTED** [review]
I can confirm that this is working like a charm! Thank you!

I had a minor comment about the error message

File: src/EntityComponentManager.cc (hunk 1 above)
Comment (chapulina) [reply src/EntityComponentManager.cc:503]: Or alternatively, this could say something like "... not expected. This is an internal error."

I don't think we usually ask that users submit users, it's kind of implied. What do you think?

File: src/systems/user_commands/UserCommands.cc [hunk 2]
```diff
@@ -1823,13 +1823,23 @@ bool VisualCommand::Execute()
...
 
-  if (visualMsg->id() == kNullEntity)
+  Entity visualEntity = kNullEntity;
+  std::string entityName = visualMsg->name();
+  if (!entityName.empty())
+  {
+    visualEntity =
+        this->iface->ecm->EntityByComponents(components::Name(entityName));
+  }
+  else if (visualMsg->id() != kNullEntity)
```
Comment (chapulina) [inline src/systems/user_commands/UserCommands.cc:1833]: It's better to check the ID before the name. IDs are unique, while names aren't. The name usually needs to be used in conjunction with the `parent_name` or `parent_id` to narrow down what the exact entity.

File: src/EntityComponentManager.cc (hunk 1 above)
Comment (jennuine) [reply src/EntityComponentManager.cc]: bb7f37e0289cdde223571b2444a7be71594a55f0 I modified the error message to follow this format: https://github.com/gazebosim/gz-sim/blob/afd087055f87d3e4c199d8e786fbccd68d3c80c1/src/EntityComponentManager.cc#L1165-L1167

File: src/systems/user_commands/UserCommands.cc (hunk 2 above)
Comment (jennuine) [reply src/systems/user_commands/UserCommands.cc]: I used `parent_name`  bb7f37e0289cdde223571b2444a7be71594a55f0
