### PR TITLE
Fix issue #2566: Prevent follow actor plugin from crashing when actor is removed

### LINKED ISSUE #2566: Crash after removing model with FollowActor plugin
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
    source build
    gz-sim version: f600a441951c6ec0818008283b051a7770da1cd6
    built with 
    gcc version: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
    build options: -DCMAKE_BUILD_TYPE=Coverage
    also reproduced on binary build with version 8.6.0

## Description
* Expected behavior: Gazebo doesn't crash
* Actual behavior: Gazebo crashes

## Steps to reproduce
1. gz sim gz-sim/examples/worlds/follow_actor.sdf -r
2. call /world/actors/remove service, with

```bash
gz service --timeout 10000 -s /world/actors/remove --reptype gz.msgs.Boolean --reqtype gz.msgs.Entity --req 'id: 12
name: "green_box"'
```
removing model with FollowActor plugin like the green box from GUI works as well.

## Output
```
Stack trace (most recent call last):
#23   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#22   Object "gz sim /tmp/exp/e_214/a.sdf --seed 1725201111 -v 0 -r -s --headless-rendering", at 0x56232226f1c4, in _start
#21   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff1a7afde3f, in __libc_start_main
#20   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7ff1a7afdd8f, in 
#19   Object "gz sim /tmp/exp/e_214/a.sdf --seed 1725201111 -v 0 -r -s --headless-rendering", at 0x56232226f17e, in 
#18   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7da5e19, in ruby_run_node
#17   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7da2317, in 
#16   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7f3733c, in rb_vm_exec
#15   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7f31cc6, in 
#14   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7f2eff5, in 
#13   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7f2cc64, in 
#12   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7ff1a3ada44b, in 
#11   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7ff1a7efa0b8, in rb_nogvl
#10   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7ff1a3ad9d6b, in 
#9    Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7ff1a3acb492, in 
#8    Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7ff1a3acee2d, in 
#7    Object "/data/play/robot/workspace/install/lib/libgz-sim8-gz.so.8.6.0", at 0x7ff1a2e22d7d, in runServer
#6    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7ff1a14a0692, in gz::sim::v8::Server::Run(bool, unsigned long, bool)
#5    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7ff1a14cc107, in 
#4    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7ff1a14fcab4, in gz::sim::v8::SimulationRunner::Run(unsigned long)
#3    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7ff1a14fd8d2, in gz::sim::v8::SimulationRunner::Step(gz::sim::v8::UpdateInfo const&)
#2    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7ff1a14f9aa8, in gz::sim::v8::SimulationRunner::UpdateSystems()
#1    Object "/data/play/robot/workspace/install/lib/gz-sim-8/plugins/libgz-sim-follow-actor-system.so", at 0x7ff164b39222, in gz::sim::v8::systems::FollowActor::PreUpdate(gz::sim::v8::UpdateInfo const&, gz::sim::v8::EntityComponentManager&)
#0    Object "/data/play/robot/workspace/install/lib/libgz-sim8-gz.so.8.6.0", at 0x7ff1a2e4ef9b, in gz::math::v7::Pose3<double>::Pose3(gz::math::v7::Pose3<double> const&)
Segmentation fault (Address not mapped to object [0x8])
```

### PR DESCRIPTION
**Pull request by arjo129**
# 🦟 Bug fix

Fixes #2566

## Summary
Adds a simple check that the entities are still in the scene.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

File: src/systems/follow_actor/FollowActor.cc [hunk 1]
```diff
@@ -209,7 +209,9 @@ void FollowActor::PreUpdate(const UpdateInfo &_info,
   this->dataPtr->lastUpdate = _info.simTime;
 
   // Is there a follow target?
-  if (this->dataPtr->targetEntity == kNullEntity)
+  if (this->dataPtr->targetEntity == kNullEntity ||
+    _ecm.HasEntity(this->dataPtr->targetEntity) ||
+    _ecm.HasEntity(this->dataPtr->actorEntity))
```
Comment (iche033) [inline src/systems/follow_actor/FollowActor.cc:214]: I think this should be:

```suggestion
  if (this->dataPtr->targetEntity == kNullEntity ||
    !_ecm.HasEntity(this->dataPtr->targetEntity) ||
    !_ecm.HasEntity(this->dataPtr->actorEntity))
```
