### PR TITLE
Fixed Odometry Publisher Angular Velocity Singularity in 3D

### LINKED ISSUE #2347: Odometry Publisher Angular Velocity Singularity in 3D
## Environment
* OS Version: Ubuntu 22.04
* gz-sim8, https://github.com/gazebosim/gz-sim/commit/1d5114bb0614b995220a9fa7d30d8d5d2da576a0

## Description
* Expected behavior: Publishing consistent angular velocities in 3 dimensions, even when rotating in gimbal lock rotations (such as pitch = 90deg)
* Actual behavior: Angular velocity becomes a very high value when the vehicle rotates to a gimbal lock rotation
* 
angular_velocity_bug

## Resolution

The angular velocities were calculated using the Euler angles, which can lead to singularities. I was able to resolve the issue by utilizing the quaternion rotation representation of the model. I created a pull request with the fix (linking this issue).

### PR DESCRIPTION
**Pull request by tomcreutz**
# 🦟 Bug fix

Fixes #2347

## Summary

The angular velocity was calculated using euler angles which led to singularities (see #2347 for a more detailed description). In addition to the fix, I also removed the usage of the rolling mean accumulator for angular velocity. While I see its usefulness for outlier rejections, I still didn't really see why this would be necessary. If the maintainers want to keep this mean accumulator, I'll be happy to reimplement it. Also the commit changes seem a bit messy, I was using clang format with the Google C++ Style guide as configuration, which leaded to the changed formatting that you can see in the pull request.

## Checklist
- [x] Signed all commits for DCO
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by tomcreutz** [comment]
Hi @mjcarroll,
is there anything more that needs to be changed to merge this pull request ?

**Comment by tomcreutz** [comment]
Hello @mjcarroll,
are there any news or requests from your side regarding this pull request ? Are there any plans to address this issue ?

File: src/systems/odometry_publisher/OdometryPublisher.cc [hunk 1]
```diff
@@ -92,10 +92,6 @@ class gz::sim::systems::OdometryPublisherPrivate
   public: std::tuple<math::RollingMean, math::RollingMean, math::RollingMean>
     linearMean;
 
-  /// \brief Rolling mean accumulators for the angular velocity
```
Comment (shameekganguly) [inline src/systems/odometry_publisher/OdometryPublisher.cc:95]: I think this change in behavior can be risky since users depending on the published angular velocity to be reasonably smooth might be broken by non-smooth values coming out of the finite difference on line 370. Could you kindly add the filter back? I'd suggest to open a follow up PR that accepts a moving average window size parameter in the System's xml input that the user can use to configure the size of the filter for both linear and angular velocities.

File: src/systems/odometry_publisher/OdometryPublisher.cc [hunk 2]
```diff
@@ -375,10 +365,14 @@ void OdometryPublisherPrivate::UpdateOdometry(
...
-  const double lastYaw = this->lastUpdatePose.Rot().Yaw();
-  while (currentYaw < lastYaw - GZ_PI) currentYaw += 2 * GZ_PI;
-  while (currentYaw > lastYaw + GZ_PI) currentYaw -= 2 * GZ_PI;
-  const float yawDiff = currentYaw - lastYaw;
+  // calculate rotation difference using the rotation as quaternion between
+  // the current and previous timestep
+  const math::Quaterniond rotationDiff = pose.Rot() *
+    this->lastUpdatePose.Rot().Inverse();
+  // calculate the angular velocity from the euler vector (radians) and dt
+  const math::Vector3d angularVelocity = rotationDiff.Euler() / dt.count();
```
Comment (shameekganguly) [inline src/systems/odometry_publisher/OdometryPublisher.cc:373]: nit: While the numerical values should be close for small enough dt, I think the following conversion from the Quaternion rotation difference to angular velocity might be more readable:
```
math::Vector3d rotationAxis;
double rotationAngle;
rotationDiff.AxisAngle(rotationAxis, rotationAngle);
const math::Vector3d angularVelocity = (rotationAngle / dt.count()) * rotationAxis;
```
Also consider moving this logic to a static `RotationDiffToAngularVelocity(...)` helper function in `OdometryPublisherPrivate`.

**Review by shameekganguly — CHANGES_REQUESTED** [review]
Please consider adding a test case in https://github.com/gazebosim/gz-sim/blob/gz-sim8/test/integration/odometry_publisher.cc to prevent a regression in computing 3d angular velocity close to singularity. Thank you!

**Comment by azeey** [comment]
I've merged https://github.com/tomcreutz/gz-sim/pull/1

File: src/systems/odometry_publisher/OdometryPublisher.cc (hunk 1 above)
Comment (shameekganguly) [reply src/systems/odometry_publisher/OdometryPublisher.cc]: Fixed in [10082f9](https://github.com/gazebosim/gz-sim/pull/2348/commits/10082f9ffd9989abcd80546b5e8d682d444eda3f)

File: src/systems/odometry_publisher/OdometryPublisher.cc (hunk 2 above)
Comment (shameekganguly) [reply src/systems/odometry_publisher/OdometryPublisher.cc]: Fixed in [daf8f0d](https://github.com/gazebosim/gz-sim/pull/2348/commits/daf8f0df25f8bae27c62a4b024fe4d8a984260ea)

**Comment by shameekganguly** [comment]
> Please consider adding a test case in https://github.com/gazebosim/gz-sim/blob/gz-sim8/test/integration/odometry_publisher.cc to prevent a regression in computing 3d angular velocity close to singularity. Thank you!

Added test case in [5b877ca](https://github.com/gazebosim/gz-sim/pull/2348/commits/5b877cab44b284cfbb1c224034b0567478bed3c7)

**Review by shameekganguly — APPROVED** [review]

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by shameekganguly** [comment]
Looks like Windows CI is failing as M_PI cannot be found. I guess we should `GZ_PI` instead in test/integration/odometry_publisher.cc

File: test/integration/odometry_publisher.cc [hunk 3]
```diff
@@ -380,6 +380,86 @@ class OdometryPublisherTest
...
+      };
+
+    // Create node for publishing twist messages
+    transport::Node node;
+    auto cmdVel = node.Advertise<msgs::Twist>("/model/test_body/cmd_vel");
+    node.Subscribe(_odomTopic, odomCb);
+
+    // Set an angular velocity command that would cause pitch to update from 0
+    // to PI in 1 second, crossing the singularity when pitch is PI/2.
+    const math::Vector3d angVelCmd(0.0, M_PI, 0);
```
Comment (shameekganguly) [inline test/integration/odometry_publisher.cc:429]:
```suggestion
    const math::Vector3d angVelCmd(0.0, GZ_PI, 0);
```

**Comment by tomcreutz** [comment]
Thank you very much for your efforts @azeey and @shameekganguly . Just returned back from holidays and wanted to take care of this in the following days.

File: test/integration/odometry_publisher.cc (hunk 3 above)
Comment (azeey) [reply test/integration/odometry_publisher.cc]: Fixed in https://github.com/gazebosim/gz-sim/pull/2348/commits/90476c04124ee52ad07a602e6fe4df4547ad1a39

Comment (shameekganguly) [reply test/integration/odometry_publisher.cc]: Thanks!

**Review by azeey — APPROVED** [review]

**Comment by azeey** [comment]
Not sure why CI on Jammy failed. The test seems completely unrelated to this PR, so I'm rerunning it to see if it's a flake. The previous CI job was green https://build.osrfoundation.org/job/gz_sim-ci-pr_any-jammy-amd64/744/.
