### PR TITLE
Prevent duplicate loading of default systems with legacy ignition plugins

### LINKED ISSUE #3179: "ignition" plugins cause plugin duplication
## Environment
* OS Version: Any
* Source or binary build? `main`.

## Description
* Expected behavior: Default plugins are not loaded if explicitly added in the SDF.
* Actual behavior: 

Starting in gz-sim9 (https://github.com/gazebosim/gz-sim/pull/2497), Gazebo now loads default plugins even if there are world level plugins included. The loading mechanism does not load a default plugin if the same plugin is explicitly instantiated in the SDF file. However, it uses a simple name check to do this and does not properly handle plugins that use their `ignition` name. Thus, when loading old SDF files that contain `ignition::gazebo::systems::Physics`, it ends up loading the `Physics` system twice.

The following server log is an excerpt from running  
 
 `gz sim -v4 "https://fuel.gazebosim.org/1.0/OpenRobotics/worlds/NAO joint control" -s`

This shows that the `Physics`, `SceneBroadcaster` and `UserCommands` systems are loaded twice.

```txt
(2025-11-07 13:07:02.566) [warning] [SystemLoader.cc:132] Trying to load deprecated plugin [ignition-gazebo-physics-system]. Using [gz-sim-physics-system] instead.
(2025-11-07 13:07:02.573) [warning] [SystemLoader.cc:74] Trying to load deprecated plugin name [ignition::gazebo::systems::Physics]. Using [gz::sim::systems::Physics] instead.
(2025-11-07 13:07:02.593) [debug] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::Physics] for entity [1]
(2025-11-07 13:07:02.593) [warning] [SystemLoader.cc:132] Trying to load deprecated plugin [ignition-gazebo-user-commands-system]. Using [gz-sim-user-commands-system] instead.
(2025-11-07 13:07:02.598) [warning] [SystemLoader.cc:74] Trying to load deprecated plugin name [ignition::gazebo::systems::UserCommands]. Using [gz::sim::systems::UserCommands] instead.
(2025-11-07 13:07:02.600) [debug] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::UserCommands] for entity [1]
(2025-11-07 13:07:02.600) [warning] [SystemLoader.cc:132] Trying to load deprecated plugin [ignition-gazebo-scene-broadcaster-system]. Using [gz-sim-scene-broadcaster-system] instead.
(2025-11-07 13:07:02.605) [warning] [SystemLoader.cc:74] Trying to load deprecated plugin name [ignition::gazebo::systems::SceneBroadcaster]. Using [gz::sim::systems::SceneBroadcaster] instead.
(2025-11-07 13:07:02.605) [debug] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::SceneBroadcaster] for entity [1]
(2025-11-07 13:07:02.614) [debug] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::JointPositionController] for entity [4]
(2025-11-07 13:07:02.615) [debug] [SystemManager.cc:80] Loaded system [gz::sim::systems::Physics] for entity [1]
(2025-11-07 13:07:02.616) [debug] [SystemManager.cc:80] Loaded system [gz::sim::systems::UserCommands] for entity [1]
(2025-11-07 13:07:02.617) [debug] [SystemManager.cc:80] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
```

The resulting simulation is unusable:

https://github.com/user-attachments/assets/8e21f166-1443-435f-a4fe-69d1837b516f

In contrast, on gz-sim8, the plugins are only loaded once.

```txt

(2025-11-07T13:11:17.483486000) [Wrn] [SystemLoader.cc:75] Trying to load deprecated plugin [ignition-gazebo-physics-system]. Using [gz-sim-physics-system] instead.
(2025-11-07T13:11:21.12437000) [Wrn] [SystemLoader.cc:136] Trying to load deprecated plugin name [ignition::gazebo::systems::Physics]. Using [gz::sim::systems::Physics] instead.
(2025-11-07T13:11:22.212426000) [Dbg] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::Physics] for entity [1]
(2025-11-07T13:11:22.212456000) [Wrn] [SystemLoader.cc:75] Trying to load deprecated plugin [ignition-gazebo-user-commands-system]. Using [gz-sim-user-commands-system] instead.
(2025-11-07T13:11:22.310638000) [Wrn] [SystemLoader.cc:136] Trying to load deprecated plugin name [ignition::gazebo::systems::UserCommands]. Using [gz::sim::systems::UserCommands] instead.
(2025-11-07T13:11:22.312227000) [Dbg] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::UserCommands] for entity [1]
(2025-11-07T13:11:22.312263000) [Wrn] [SystemLoader.cc:75] Trying to load deprecated plugin [ignition-gazebo-scene-broadcaster-system]. Using [gz-sim-scene-broadcaster-system] instead.
(2025-11-07T13:11:22.413533000) [Wrn] [SystemLoader.cc:136] Trying to load deprecated plugin name [ignition::gazebo::systems::SceneBroadcaster]. Using [gz::sim::systems::SceneBroadcaster] instead.
(2025-11-07T13:11:22.413664000) [Dbg] [SystemManager.cc:80] Loaded system [ignition::gazebo::systems::SceneBroadcaster] for entity [1]
```

https://github.com/user-attachments/assets/a6230f0f-25ce-414a-88f8-455d32fdce26

## Steps to reproduce

1.  Run  `gz sim -v4 "https://fuel.gazebosim.org/1.0/OpenRobotics/worlds/NAO joint control" -s`

### PR DESCRIPTION
**Pull request by naitikpahwa18**
# 🦟 Bug fix

Fixes #3179 

## Summary
This fixes a regression introduced in gz-sim9 where default systems
(Physics, UserCommands, SceneBroadcaster) are loaded even when the same
systems are explicitly specified in the world SDF using legacy
ignition::gazebo plugin names.

The duplicate check previously compared raw plugin filenames.
This change normalizes plugin filenames to canonical gz forms before
comparison, ensuring ignition and gz plugin aliases are treated as the
same system and preventing duplicate loading.

Reproduced with the NAO joint control world on gz-sim 9.5.0.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers
- [ ] Was GenAI used to generate this PR? If so, make sure to add "Generated-by" to your commits. (See [this policy](https://osralliance.org/wp-content/uploads/2025/05/OSRF-Policy-on-the-Use-of-Generative-Tools-Generative-AI-in-Contributions.pdf) for more info.)
      
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.

### CODE REVIEW

File: src/SimulationRunner.cc [hunk 1]
```diff
@@ -100,6 +101,36 @@ struct MaybeGilScopedRelease
...
+  if (_name.empty())
+    return _name;
+
+  const std::string prefix{"ignition::gazebo::"};
+  if (common::StartsWith(_name, prefix))
+  {
+    return "gz::sim::" + _name.substr(prefix.size());
+  }
+
+  return _name;
```
[the remark this answers is not in the document]
Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: Applied, updated filename normalization to mirror SystemLoader behavior for deprecated ignition-gazebo libraries.

File: src/SimulationRunner.cc [hunk 2]
```diff
@@ -1736,15 +1772,32 @@ void SimulationRunner::CreateEntities()
...
+          auto name = NormalizePluginName(_pl.Plugin().Name());
+          if (!name.empty() && loadedWorldPluginNames.count(name) > 0)
+            return true;
+
+          auto filename = NormalizePluginFilename(_pl.Plugin().Filename());
+          if (!filename.empty() &&
+              loadedWorldPluginFileNames.count(filename) > 0)
+            return true;
+
+          return false;
```
[the remark this answers is not in the document]
Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: Agreed, adding a regression test would be valuable. I kept this PR focused on fixing the loading regression. Happy to follow up with a test if maintainers would like one added here.

File: src/SimulationRunner.cc [hunk 3]
```diff
@@ -100,6 +101,41 @@ struct MaybeGilScopedRelease
...
+
+  std::string result = _filename;
+  std::size_t pos = 0;
+  while ((pos = result.find(deprecated, pos)) != std::string::npos)
+  {
+    result.replace(pos, deprecated.size(), current);
+    pos += current.size();
+  }
+
+  return result;
```
[the remark this answers is not in the document]
Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: Keeping the normalization logic local for now to keep this PR focused on fixing the duplicate-loading regression. Happy to follow up with a shared helper if maintainers prefer.

File: src/SimulationRunner.cc [hunk 4]
```diff
@@ -100,6 +101,41 @@ struct MaybeGilScopedRelease
...
+// duplicate detection while keeping namespace-safe behavior.
+std::string NormalizePluginName(const std::string &_name)
+{
+  if (_name.empty())
+    return _name;
+
+  const std::string prefix{"ignition::gazebo::"};
+  if (common::StartsWith(_name, prefix))
+  {
+    return "gz::sim::" + _name.substr(prefix.size());
```
Comment (arjo129) [inline src/SimulationRunner.cc]: Might be worth printing a warning asking the users to migrate their sdf.

Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: I've added a per-plugin warning for deprecated ignition plugin identifiers.

**Comment by arjo129** [comment]
@azeey just for sanity, as you are most familiar with the changes involved in this part do you mind doing a review pass for this?

File: src/SimulationRunner.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (arjo129) [reply src/SimulationRunner.cc]: I think copilot is right here.

**Comment by naitikpahwa18** [comment]
Refactored normalization into shared helpers in gz::sim::Util and reused them in both SimulationRunner and SystemLoader to avoid duplication.

File: src/SimulationRunner.cc [hunk 5]
```diff
@@ -1736,15 +1757,32 @@ void SimulationRunner::CreateEntities()
...
     {
-      std::unordered_set<std::string> loadedWorldPluginFileNames;
+      StringSet loadedWorldPluginNames;
+      StringSet loadedWorldPluginFileNames;
       for (const auto &pl : loadedWorldPlugins)
       {
-        loadedWorldPluginFileNames.insert(pl.fname);
+        auto name = NormalizePluginName(pl.name);
+        if (!name.empty())
+          loadedWorldPluginNames.insert(name);
```
[the remark this answers is not in the document]
Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: I can follow up with an integration/regression test if maintainers prefer coverage here.

[the remark this answers is not in the document]
Comment (arjo129) [reply src/SimulationRunner.cc]: Yeah that'd be great

[the remark this answers is not in the document]
Comment (arjo129) [reply src/SimulationRunner.cc]: Yeah that'd be great

[the remark this answers is not in the document]
Comment (arjo129) [reply src/SimulationRunner.cc]: Yeah that'd be great

**Comment by naitikpahwa18** [comment]
Hi @azeey and @arjo129, just a quick reminder to check this out when you get a chance. Thanks!

**Review by arjo129 — APPROVED** [review]

**Comment by arjo129** [comment]
Hey — thanks for the follow-ups and for your enthusiasm. Just a heads-up that repeated pings don’t speed things up and actually make it harder to manage.

@azeey is the expert on this part, and he’ll need to review it. He is currently out, so there may be some delay. We’ll follow up once they’re back and have had a chance to look.

**Comment by naitikpahwa18** [comment]
Thanks for the heads-up, and sorry about that. I’m still getting familiar with the workflow here and will be more mindful going forward. Appreciate the guidance.

File: src/Util.cc [hunk 6]
```diff
@@ -183,6 +183,46 @@ std::string scopedName(const Entity &_entity,
   return result;
 }
 
+//////////////////////////////////////////////////
+std::string normalizePluginName(const std::string &_name)
+{
+  std::string result = _name;
+  const std::string deprecated{"ignition::gazebo"};
+  const std::string current{"gz::sim"};
```
Comment (azeey) [inline src/Util.cc]: nitpick: Consider making these `std::string_view` to avoid unnecessary memory allocations.

File: src/Util.cc [hunk 7]
```diff
@@ -183,6 +183,46 @@ std::string scopedName(const Entity &_entity,
...
+  std::string::size_type pos = 0;
+  while ((pos = result.find(deprecated, pos)) != std::string::npos)
```
Comment (azeey) [inline src/Util.cc]: I'm not convinced that we need to replace multiple occurences. If there are multiple occurences of `ignition::gazebo` in the name, it's probably not a core plugin. Maybe it's a user plugin and we shouldn't touch it. If `ignition::gazebo` is not at position 0, that's also something we should skip.

File: src/Util.cc [hunk 8]
```diff
@@ -183,6 +183,46 @@ std::string scopedName(const Entity &_entity,
...
+{
+  std::string result = _filename;
+  const std::string deprecated{"ignition-gazebo"};
+  const std::string current{"gz-sim"};
+  std::string::size_type pos = 0;
+  while ((pos = result.find(deprecated, pos)) != std::string::npos)
+  {
+    result.replace(pos, deprecated.size(), current);
+    pos += current.size();
+  }
```
Comment (azeey) [inline src/Util.cc]: Same comment here about multiple occurences as above.

File: test/integration/legacy_default_plugins.cc [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+</sdf>)";
+}
+}
+
+class LegacyDefaultPluginsTest : public InternalFixture<::testing::Test>
+{
+};
+
+/////////////////////////////////////////////////
+TEST_F(LegacyDefaultPluginsTest, DoesNotDuplicateDefaultSystems)
```
Comment (azeey) [inline test/integration/legacy_default_plugins.cc:65]: Nice test! I like how you compared it with a baseline world.

File: src/SimulationRunner.cc [hunk 10]
```diff
@@ -1736,15 +1737,33 @@ void SimulationRunner::CreateEntities()
...
-          return loadedWorldPluginFileNames.count(_pl.Plugin().Filename()) != 0;
+          auto name = gz::sim::normalizePluginName(_pl.Plugin().Name());
+          if (!name.empty() && loadedWorldPluginNames.count(name) > 0)
+            return true;
+
+          auto filename =
+              gz::sim::normalizePluginFilename(_pl.Plugin().Filename());
+          if (!filename.empty() &&
+              loadedWorldPluginFileNames.count(filename) > 0)
+            return true;
```
Comment (azeey) [inline src/SimulationRunner.cc]: Matching plugin names is not a sufficient condition to consider a plugin is already loaded since, at least in theory, it's possible to have the same plugin name but have different file names.

It's not common practice, but it is technically possible to have multiple plugins in one shared library too, so we should really be checking the uniquness of the plugin name and filename combination. However, I think for now, it is sufficient to just check the filename as it was done originally.

File: include/gz/sim/Util.hh [hunk 11]
```diff
@@ -160,6 +160,18 @@ namespace gz
     std::string GZ_SIM_VISIBLE removeParentScope(
         const std::string &_name, const std::string &_delim);
 
+    /// \brief Normalize deprecated ignition plugin identifiers in a plugin
+    /// name to gz equivalents.
+    /// \return Normalized plugin name.
+    std::string GZ_SIM_VISIBLE normalizePluginName(
```
Comment (azeey) [inline include/gz/sim/Util.hh:167]: nit: Add `\param[in] _name ...` to docs

**Comment by azeey** [comment]
Can you also make sure to include the full checklists in the PR description and keep the instructions for maintainers, i.e, properly fill out the PR template?

File: src/Util.cc (hunk 6 above)
Comment (naitikpahwa18) [reply src/Util.cc]: Updated `std::string` to `std::string_view`

File: src/Util.cc (hunk 7 above)
Comment (naitikpahwa18) [reply src/Util.cc]: I’ve restricted normalization to only handle a single deprecated prefix at position 0 to avoid touching user-defined plugin names.

File: include/gz/sim/Util.hh (hunk 11 above)
Comment (naitikpahwa18) [reply include/gz/sim/Util.hh:167]: Added the missing `\param[in] _name` documentation.

File: src/SimulationRunner.cc (hunk 10 above)
Comment (naitikpahwa18) [reply src/SimulationRunner.cc]: Thanks for the clarification. I’ve updated the logic to rely only on normalized plugin filenames, matching the original behavior and avoiding name-only de-duplication.

**Comment by naitikpahwa18** [comment]
Thanks for the note, I’ve updated the PR description with the full checklist, preserved the maintainer instructions, and addressed the requested changes.

File: src/Util.cc (hunk 8 above)
Comment (naitikpahwa18) [reply src/Util.cc]: I’ve updated the logic here as well to handle repeated deprecated prefixes consistently, while avoiding replacements beyond the prefix.

**Comment by arjo129** [comment]
Thanks for the great work and iteration @naitikpahwa18 !

**Comment by arjo129** [comment]
@mergifyio backport gz-sim9 gz-sim10
