### PR TITLE
Fix Ackermann plugin zero linVel turningRadius bug

### LINKED ISSUE #1848: Ackermann plugin turningRadius bug when linVel is zero
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
  binary, ignition-fortress

## Description
* Expected behavior: With Ackerman plugin wheels should point direction of steering when having no forward commanded velocity.
* Actual behavior: Wheels always rotate clockwise when linVel is zero.
## Steps to reproduce
Run MR-Buggy3 with teleop and command it to yaw right (they only point left)

## Output

https://user-images.githubusercontent.com/10233412/209772618-b0a06ad2-28dd-4d53-988e-22d568f7209f.mp4

### PR DESCRIPTION
**Pull request by bperseghetti**
# 🦟 Bug fix

Fixes #1848

## Summary
Fix for handling Ackermann wheel steering angle bug where wheel always points same direction when linVel is zero and abs(angVel) > 0.001. This results in an always positive evaluated turningRadius. This solution fixes it by handling linVel zero properly. Allowing it to get past the first conditional that it is otherwise stuck on.

Now the wheels can rotate both directions when the vehicle has no linVel:

https://user-images.githubusercontent.com/10233412/209774462-ac17dd19-f537-4075-a1e4-c3b313a310fc.mp4

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: src/systems/ackermann_steering/AckermannSteering.cc [hunk 1]
```diff
@@ -729,14 +729,23 @@ void AckermannSteeringPrivate::UpdateVelocity(
...
+    {
+      turningRadius = -minimumTurningRadius;
+    }
   }
-  if ((turningRadius <= 0.0) && (turningRadius > -minimumTurningRadius))
+  // special case for angVel not zero and linVel zero
+  else if (fabs(angVel) >= 0.001)
   {
-    turningRadius = -minimumTurningRadius;
+    turningRadius = (angVel/fabs(angVel))*minimumTurningRadius*1.5;
```
Comment (jennuine) [inline src/systems/ackermann_steering/AckermannSteering.cc:746]: The `1.5` multiplication appears to be unneeded (everything is working as expected when removed). If it is needed, can you explain why?
```suggestion
    turningRadius = (angVel / fabs(angVel)) * minimumTurningRadius;
```

**Review by jennuine — COMMENTED** [review]
LGTM, left a minor comment

File: src/systems/ackermann_steering/AckermannSteering.cc (hunk 1 above)
Comment (bperseghetti) [reply src/systems/ackermann_steering/AckermannSteering.cc:746]: Well, it comes down to the calculation of the turningRadius. This "1.5 x increase in size" of the turning radius only applies when there is zero linVel. For some reason it felt odd to force the wheels completely to their limits even if the angVel was only .001 but the linVel is zero simply because it's not being commanded, seems to have the effect of making the vehicle "dance" as that angle can be very aggressive. From a strictly "this should only be used with teleop or twist" perspective I see your point though.

I suppose maybe it's my overall dislike of the Ackermann Plugin using the twist message for angular velocity instead of setting a steering angle slowly working it's way through into the code. 

But for sake of cohesiveness of the intention of the plugin, I'll commit that suggested change.
Hopefully we can get this fix in ASAP and rolled into a spot release.

**Review by bperseghetti — COMMENTED** [review]
@jennuine did a quick test and seems to work fine.

**Review by jennuine — APPROVED** [review]
We need to wait for CI before this can be merged and a new release made. If I can't get to it tonight, it will be finished tomorrow

**Comment by bperseghetti** [comment]
> We need to wait for CI before this can be merged and a new release made. If I can't get to it tonight, it will be finished tomorrow

Thanks @jennuine! Really appreciate it!

**Review by ahcorde — APPROVED** [review]

**Comment by bperseghetti** [comment]
@ahcorde @jennuine @mjcarroll thank you all for the expediency on getting this bug fixed, does anyone know when the next forward port to gz-sim7? looks like the last was: https://github.com/gazebosim/gz-sim/pull/1832. Also I think that there has not been a new point release for garden in a while (https://github.com/gazebosim/gz-sim/commit/39520a12b11c88d11160b0b58c5d59bb6985dde3), looks like the motor plugin update wasn't included as well in last point release: https://github.com/gazebosim/gz-sim/pull/1794.

**Comment by mjcarroll** [comment]
I'm going to try to get a forward port and point release out today for you.
