### PR TITLE
Fix adding system to non-existent entity

### LINKED ISSUE #2508: Crash after dynamically adding plugin LiftDrag to non-existing entity
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
    source build
    gz-sim version: 907efc31f6ff5de0e5d32922f054601e643588f2
    built with 
    gcc version: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
    build options: -DCMAKE_BUILD_TYPE=Coverage

## Description
* Expected behavior: Gazebo doesn't crash
* Actual behavior: Gazebo crashes

## Steps to reproduce
1. gz sim [a.txt](https://github.com/user-attachments/files/16485367/a.txt) -r # an empty world with name world_0
2. add plugin LiftDrag with gz service command, to a non-existing entity id

```bash
gz service --timeout 10000 -s /world/world_0/entity/system/add --reptype gz.msgs.Boolean --reqtype gz.msgs.EntityPlugin_V --req 'entity {
  id: 47
}
plugins {
  name: "gz::sim::systems::LiftDrag"
  filename: "gz-sim-lift-drag-system"
  innerxml: "<a0>0.1</a0>\n        \n<cla>0.1</cla>\n        \n<cda>0.001</cda>\n        \n<cma>0.0</cma>\n        \n<cp>0.0 0.5 0</cp>\n        \n<area>0.2</area>\n        \n<air_density>1.2041</air_density>\n        \n<forward>1 0 0</forward>\n        \n<upward>0 0 1</upward>\n        \n<link_name>blade_2::link</link_name>\n      "
}'

```
could also be reproduced by extracting [a.tar.gz](https://github.com/user-attachments/files/16485370/a.tar.gz), and then run
```bash
bash a.sh
```

## Output
```
[Err] [EntityComponentManager.cc:1083] Trying to create a component of type [9904571861011273795] attached to entity [47], but this entity does not exist. This create component request will be ignored.
[Err] [LiftDrag.cc:537] The LiftDrag system should be attached to a model entity. Failed to initialize.
Stack trace (most recent call last):
#31   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab5dce19, in ruby_run_node
#30   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab5d9317, in
#29   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab76e33c, in rb_vm_exec
#28   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab768cc6, in
#27   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab765ff5, in
#26   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab763c64, in
#25   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab6afa4e, in
#24   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab5da9ac, in rb_protect
#23   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab772c91, in rb_yield
#22   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab76e33c, in rb_vm_exec
#21   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab768cc6, in
#20   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab765ff5, in
#19   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab763c64, in
#18   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7f91a731144b, in
#17   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f91ab7310b8, in rb_nogvl
#16   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7f91a7310d6b, in
#15   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7f91a7302492, in
#14   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7f91a7305e2d, in
#13   Object "/data/play/robot/workspace/install/lib/libgz-sim8-gz.so.8.6.0", at 0x7f91a6659d7d, in runServer
#12   Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4d1356a, in gz::sim::v8::Server::Run(bool, unsigned long, bool)
#11   Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4d3efdf, in
#10   Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4d6fd84, in gz::sim::v8::SimulationRunner::Run(unsigned long)
#9    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4d70ba2, in gz::sim::v8::SimulationRunner::Step(gz::sim::v8::UpdateInfo const&)
#8    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4d6cf2a, in gz::sim::v8::SimulationRunner::UpdateSystems()
#7    Object "/data/play/robot/workspace/install/lib/gz-sim-8/plugins/libgz-sim-lift-drag-system.so", at 0x7f91664a48a1, in gz::sim::v8::systems::LiftDrag::PreUpdate(gz::sim::v8::UpdateInfo const&, gz::sim::v8::EntityComponentManager&)
#6    Object "/data/play/robot/workspace/install/lib/gz-sim-8/plugins/libgz-sim-lift-drag-system.so", at 0x7f916649ee5e, in gz::sim::v8::systems::LiftDragPrivate::Load(gz::sim::v8::EntityComponentManager const&, std::shared_ptr<sdf::v14::Element> const&)
#5    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4b94f9c, in std::pair<double, bool> sdf::v14::Element::Get<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double const&) const
#4    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f91a4b9f902, in std::pair<double, bool> sdf::v14::Element::Get<double>(std::vector<sdf::v14::Error, std::allocator<sdf::v14::Error> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double const&) const
#3    Object "/home/ren/play/robot/workspace/install/lib/libsdformat14.so.14", at 0x7f91a2a0fda6, in sdf::v14::Element::GetAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
#2    Object "/home/ren/play/robot/workspace/install/lib/libsdformat14.so.14", at 0x7f91a295dc43, in
#1    Object "/home/ren/play/robot/workspace/install/lib/libsdformat14.so.14", at 0x7f91a296b99b, in
#0    Object "/home/ren/play/robot/workspace/install/lib/libsdformat14.so.14", at 0x7f91a2973d7e, in
    Segmentation fault (Address not mapped to object [0x18])
```

### LINKED ISSUE #2511: Crash after dynamically adding plugin LinearBatteryPlugin to non-existing entity
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
    source build
    gz-sim version: 907efc31f6ff5de0e5d32922f054601e643588f2
    built with 
    gcc version: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
    build options: -DCMAKE_BUILD_TYPE=Coverage

## Description
* Expected behavior: Gazebo doesn't crash
* Actual behavior: Gazebo crashes

## Steps to reproduce
1. gz sim [a.txt](https://github.com/user-attachments/files/16493509/a.txt) -r
2. add plugin LinearBatteryPlugin with gz service command, to a non-existing entity id

```bash
gz service --timeout 10000 -s /world/world_0/entity/system/add --reptype gz.msgs.Boolean --reqtype gz.msgs.EntityPlugin_V --req 'entity {
  id: 100
}
plugins {
  name: "gz::sim::systems::LinearBatteryPlugin"
  filename: "gz-sim-linearbatteryplugin-system"
  innerxml: "<!--Li-ion battery spec from LIR18650 datasheet-->\n        \n<battery_name>linear_battery</battery_name>\n        \n<voltage>4.2</voltage>\n        \n<open_circuit_voltage_constant_coef>4.2</open_circuit_voltage_constant_coef>\n        \n<open_circuit_voltage_linear_coef>-2.0</open_circuit_voltage_linear_coef>\n        \n<initial_charge>2.5</initial_charge>\n        \n<capacity>2.5 </capacity>\n        \n<resistance>0.07</resistance>\n        \n<smooth_current_tau>2.0</smooth_current_tau>\n        \n<enable_recharge>true</enable_recharge>\n        \n<!-- charging I = c / t, discharging I = P / V,\n          charging I should be > discharging I -->\n        \n<charging_time>3.0</charging_time>\n        \n<!-- Consumer-specific -->\n        \n<power_load>2.1</power_load>\n        \n<start_on_motion>true</start_on_motion>\n      "
}'
```
or

1. tar xf [a.tar.gz](https://github.com/user-attachments/files/16493551/a.tar.gz)
2. bash a.sh

This crash is similar to #2508, but the fix seems to be different?
## Output
```
[Err] [EntityComponentManager.cc:1083] Trying to create a component of type [9904571861011273795] attached to entity [100], but this entity does not exist. This create component request will be ignored.
[Err] [LinearBatteryPlugin.cc:219] Linear battery plugin should be attached to a model entity. Failed to initialize.

Stack trace (most recent call last):
#31   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f9b3ef24e3f, in __libc_start_main
#30   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f9b3ef24d8f, in
#29   Object "gz sim server", at 0x5562e6baf17e, in
#28   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f1cce19, in ruby_run_node
#27   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f1c9317, in
#26   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f35e33c, in rb_vm_exec
#25   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f358cc6, in
#24   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f355ff5, in
#23   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f353c64, in
#22   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f29fa4e, in
#21   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f1ca9ac, in rb_protect
#20   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f362c91, in rb_yield
#19   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f35e33c, in rb_vm_exec
#18   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f358cc6, in
#17   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f355ff5, in
#16   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f353c64, in
#15   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7f9b3af0144b, in
#14   Object "/lib/x86_64-linux-gnu/libruby-3.0.so.3.0", at 0x7f9b3f3210b8, in rb_nogvl
#13   Object "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/fiddle.so", at 0x7f9b3af00d6b, in
#12   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7f9b3aef2492, in
#11   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7f9b3aef5e2d, in
#10   Object "/data/play/robot/workspace/install/lib/libgz-sim8-gz.so.8.6.0", at 0x7f9b3a249d7d, in runServer
#9    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f9b3890356a, in gz::sim::v8::Server::Run(bool, unsigned long, bool)
#8    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f9b3892efdf, in
#7    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f9b3895fd84, in gz::sim::v8::SimulationRunner::Run(unsigned long)
#6    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f9b38960ba2, in gz::sim::v8::SimulationRunner::Step(gz::sim::v8::UpdateInfo const&)
#5    Object "/home/ren/play/robot/workspace/install/lib/libgz-sim8.so.8", at 0x7f9b3895cf2a, in gz::sim::v8::SimulationRunner::UpdateSystems()
#4    Object "/data/play/robot/workspace/install/lib/gz-sim-8/plugins/libgz-sim-linearbatteryplugin-system.so", at 0x7f9afa04d8ef, in gz::sim::v8::systems::LinearBatteryPlugin::PreUpdate(gz::sim::v8::UpdateInfo const&, gz::sim::v8::EntityComponentManager&)
#3    Object "/home/ren/play/robot/workspace/install/lib/libgz-common5.so.5", at 0x7f9b35c0a3e7, in gz::common::Battery::SetPowerLoad(unsigned int, double)
#2    Object "/home/ren/play/robot/workspace/install/lib/libgz-common5.so.5", at 0x7f9b35c0c3a9, in std::unique_ptr<gz::common::Battery::Implementation, void (*)(gz::common::Battery::Implementation*)>::operator->() const
#1    Object "/home/ren/play/robot/workspace/install/lib/libgz-common5.so.5", at 0x7f9b35c0daa9, in std::unique_ptr<gz::common::Battery::Implementation, void (*)(gz::common::Battery::Implementation*)>::get() const
#0    Object "/home/ren/play/robot/workspace/install/lib/libgz-common5.so.5", at 0x7f9b35c0f52c, in std::__uniq_ptr_impl<gz::common::Battery::Implementation, void (*)(gz::common::Battery::Implementation*)>::_M_ptr() const
Segmentation fault (Address not mapped to object [0x10])
```

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

Fixes #2508, #2511, and #2513

## Summary

* Added check for entity id before attempting to load the requested plugin.
* If entity id is not specified, default to world entity (same logic as the one implemented in [SimulationRunner](https://github.com/gazebosim/gz-sim/blob/907efc31f6ff5de0e5d32922f054601e643588f2/src/SimulationRunner.cc#L516))
* Added sanity checks for null battery objects in linear battery plugin (example plugin mentioned in #2511).

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: src/SystemManager.cc [hunk 1]
```diff
@@ -403,6 +404,19 @@ void SystemManager::ProcessPendingEntitySystems()
...
 
+    // set to world entity if entity id is not specified in the request.
+    if (entity == kNullEntity || entity == 0u)
+    {
+      entity = worldEntity(*this->entityCompMgr);
+    }
+    // otherwise check if entity exists before attempting to load the plugin.
+    else if (!this->entityCompMgr->HasEntity(entity))
+    {
+      gzwarn << "Unable to add plugins to Entity: '" << entity
```
Comment (arjo129) [inline src/SystemManager.cc:415]: Might be worth setting to `gzerr` as by default end users don't see any indication of failure unless the enable logging at higher verbosities. In addition the add service should probable return false if we fail to add a object, but by default it always returns true.

**Review by arjo129 — APPROVED** [review]
LGTM. I've only got a minor issue over the logging.

File: src/SystemManager.cc (hunk 1 above)
Comment (iche033) [reply src/SystemManager.cc]: updated this msg and the one above to `gzerr`. [510a5dd](https://github.com/gazebosim/gz-sim/pull/2516/commits/510a5ddbe85bd4d0d4b18b93dac54a20966e2022)

> In addition the add service should probable return false if we fail to add a object, but by default it always returns true.

I noticed we do that in several places in gz-sim so that the requests can be handled asynchronously. The response data `true` indicates that the request was handled but not necessarily successful. I added a todo note on this. Not sure if there's a way to set response data in an asynchronous way, maybe @caguero knows if it's currently possible?
