### PR TITLE
docs: fix doxygen parameter mismatches in core headers

### LINKED ISSUE #3371: Doxygen warnings should be fixed
## Environment
* OS Version: Ubuntu 24.04, macOS
* Source or binary build? source build of `main` branch

## Description

Doxygen checks are enabled in CI in https://github.com/gazebosim/gz-sim/pull/3157, but there are many existing warnings that need to be fixed.

* Expected behavior: `make doc` can be run without doxygen warnings
* Actual behavior: There are many warnings (see [CI logs](https://github.com/gazebosim/gz-sim/actions/runs/22809137194/job/66162990700?pr=3157) for #3157)

## Steps to reproduce

1. Check out branch for #3157 from source
2. Run `cmake` and `make doc`
3. Check contents of `gz-doxygen.warn`

## Output

Excluding errors containing `Detected potential recursive class relation between class` and `@param is not found in the argument list of Q_DECLARE_METATYPE(ComponentTypeId)`:

<details>

~~~
2026-03-07T23:07:24.6682429Z /github/workspace/src/gui/plugins/modules/EntityContextMenu.hh:43: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
...
2026-03-07T23:07:24.7120893Z /github/workspace/tutorials/resources.md:1: warning: multiple use of section label 'resources', (first occurrence: /github/workspace/tutorials/using_components.md, line 33)
2026-03-07T23:07:24.7122691Z /github/workspace/build/tutorials.md:1: warning: multiple use of section label 'tutorials', (first occurrence: /github/workspace/build/tutorials.md, line 7)
2026-03-07T23:07:24.7124424Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
...
2026-03-07T23:07:24.7329221Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7335300Z /github/workspace/tutorials/component_jointforcecmd.md:37: warning: unable to resolve reference to 'gz::sim::Model:' for \ref command
2026-03-07T23:07:24.7336199Z /github/workspace/tutorials/component_pose.md:30: warning: unable to resolve reference to 'gz::sim::Model:' for \ref command
2026-03-07T23:07:24.7336876Z /github/workspace/tutorials/detachable_joints.md:61: warning: Unsupported xml/html tag <detach_topic> found
2026-03-07T23:07:24.7337440Z /github/workspace/tutorials/lander.md:238: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7337928Z /github/workspace/tutorials/lander.md:238: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7338395Z /github/workspace/tutorials/lander.md:384: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7338905Z /github/workspace/tutorials/lander.md:384: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7339364Z /github/workspace/tutorials/lander.md:386: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7339863Z /github/workspace/tutorials/lander.md:386: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7340392Z /github/workspace/tutorials/migration_sdf.md:301: warning: Unsupported xml/html tag <material> found
2026-03-07T23:07:24.7341172Z /github/workspace/tutorials/move_camera_to_model.md:16: warning: image file files/move_camera_to_model/box_5.gif is not found in IMAGE_PATH: assuming external image.
2026-03-07T23:07:24.7342124Z /github/workspace/tutorials/move_camera_to_model.md:24: warning: image file files/move_camera_to_model/box_20.gif is not found in IMAGE_PATH: assuming external image.
2026-03-07T23:07:24.7343121Z /github/workspace/tutorials/pause_run_simulation.md:57: warning: image file files/pause_run_simulation/gui_pause_run.png is not found in IMAGE_PATH: assuming external image.
2026-03-07T23:07:24.7343996Z /github/workspace/tutorials/rendering_plugins.md:48: warning: unable to resolve reference to 'gz::gui::Plugin' for \ref command
2026-03-07T23:07:24.7344795Z /github/workspace/tutorials/rendering_plugins.md:73: warning: unable to resolve reference to 'gz::gui::events::Render' for \ref command
2026-03-07T23:07:24.7345533Z /github/workspace/tutorials/resources.md:64: warning: unable to resolve reference to 'gz::gui::plugins' for \ref command
2026-03-07T23:07:24.7346357Z /github/workspace/tutorials/resources.md:146: warning: Unsupported xml/html tag <geometry> found
2026-03-07T23:07:24.7346920Z /github/workspace/tutorials/resources.md:146: warning: Unsupported xml/html tag <mesh> found
2026-03-07T23:07:24.7347460Z /github/workspace/tutorials/resources.md:146: warning: Unsupported xml/html tag <uri> found
2026-03-07T23:07:24.7348010Z /github/workspace/tutorials/theory_buoyancy.md:35: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7348582Z /github/workspace/tutorials/theory_hydrodynamics.md:53: warning: Unsupported xml/html tag <xDotU> found
2026-03-07T23:07:24.7349212Z /github/workspace/tutorials/theory_hydrodynamics.md:54: warning: Unsupported xml/html tag <yDotV> found
2026-03-07T23:07:24.7349828Z /github/workspace/tutorials/theory_hydrodynamics.md:55: warning: Unsupported xml/html tag <zDotW> found
2026-03-07T23:07:24.7350436Z /github/workspace/tutorials/theory_hydrodynamics.md:56: warning: Unsupported xml/html tag <kDotP> found
2026-03-07T23:07:24.7351061Z /github/workspace/tutorials/theory_hydrodynamics.md:57: warning: Unsupported xml/html tag <mDotQ> found
2026-03-07T23:07:24.7351663Z /github/workspace/tutorials/theory_hydrodynamics.md:58: warning: Unsupported xml/html tag <nDotR> found
2026-03-07T23:07:24.7352269Z /github/workspace/tutorials/theory_hydrodynamics.md:59: warning: Unsupported xml/html tag <xUabsU> found
2026-03-07T23:07:24.7352876Z /github/workspace/tutorials/theory_hydrodynamics.md:60: warning: Unsupported xml/html tag <xU> found
2026-03-07T23:07:24.7353469Z /github/workspace/tutorials/theory_hydrodynamics.md:61: warning: Unsupported xml/html tag <yVabsV> found
2026-03-07T23:07:24.7354071Z /github/workspace/tutorials/theory_hydrodynamics.md:62: warning: Unsupported xml/html tag <yV> found
2026-03-07T23:07:24.7354668Z /github/workspace/tutorials/theory_hydrodynamics.md:63: warning: Unsupported xml/html tag <zWabsW> found
2026-03-07T23:07:24.7355259Z /github/workspace/tutorials/theory_hydrodynamics.md:64: warning: Unsupported xml/html tag <zW> found
2026-03-07T23:07:24.7356007Z /github/workspace/tutorials/theory_hydrodynamics.md:65: warning: Unsupported xml/html tag <kPabsP> found
2026-03-07T23:07:24.7356600Z /github/workspace/tutorials/theory_hydrodynamics.md:66: warning: Unsupported xml/html tag <kP> found
2026-03-07T23:07:24.7357192Z /github/workspace/tutorials/theory_hydrodynamics.md:67: warning: Unsupported xml/html tag <mQabsQ> found
2026-03-07T23:07:24.7357783Z /github/workspace/tutorials/theory_hydrodynamics.md:68: warning: Unsupported xml/html tag <mQ> found
2026-03-07T23:07:24.7358411Z /github/workspace/tutorials/theory_hydrodynamics.md:69: warning: Unsupported xml/html tag <nRabsR> found
2026-03-07T23:07:24.7359026Z /github/workspace/tutorials/theory_hydrodynamics.md:70: warning: Unsupported xml/html tag <nR> found
2026-03-07T23:07:24.7359651Z /github/workspace/tutorials/theory_hydrodynamics.md:71: warning: Unsupported xml/html tag <default_current> found
2026-03-07T23:07:24.7360264Z /github/workspace/tutorials/underwater_vehicles.md:90: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7360818Z /github/workspace/tutorials/underwater_vehicles.md:94: warning: Found unknown command '\frac'
2026-03-07T23:07:24.7361575Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7362562Z /github/workspace/include/gz/sim/Conversions.hh:702: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const msgs::ParticleEmitter &)
2026-03-07T23:07:24.7363565Z /github/workspace/include/gz/sim/Conversions.hh:804: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const msgs::Plugin &)
2026-03-07T23:07:24.7364574Z /github/workspace/include/gz/sim/Conversions.hh:820: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const msgs::Plugin_V &)
2026-03-07T23:07:24.7365667Z /github/workspace/include/gz/sim/Conversions.hh:738: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const msgs::Projector &)
2026-03-07T23:07:24.7366789Z /github/workspace/include/gz/sim/Conversions.hh:756: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const sdf::Element &)
2026-03-07T23:07:24.7367773Z /github/workspace/include/gz/sim/Conversions.hh:684: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const sdf::ParticleEmitter &)
2026-03-07T23:07:24.7368769Z /github/workspace/include/gz/sim/Conversions.hh:772: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const sdf::Plugin &)
2026-03-07T23:07:24.7369734Z /github/workspace/include/gz/sim/Conversions.hh:788: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const sdf::Plugins &)
2026-03-07T23:07:24.7370719Z /github/workspace/include/gz/sim/Conversions.hh:720: warning: argument '_in' of command @param is not found in the argument list of gz::sim::convert(const sdf::Projector &)
2026-03-07T23:07:24.7371726Z /github/workspace/include/gz/sim/Util.hh:364: warning: argument '_filename_' of command @param is not found in the argument list of gz::sim::isStaticPlugin(const std::string &_filename)
2026-03-07T23:07:24.7372707Z /github/workspace/include/gz/sim/Util.hh:364: warning: The following parameter of gz::sim::isStaticPlugin(const std::string &_filename) is not documented:
2026-03-07T23:07:24.7373284Z   parameter '_filename'
2026-03-07T23:07:24.7374035Z /github/workspace/include/gz/sim/Util.hh:247: warning: argument '_sdfFile' of command @param is not found in the argument list of gz::sim::resolveSdfWorldFile(const std::string &_sdfFilename, const std::string &_fuelResourceCache="")
2026-03-07T23:07:24.7375318Z /github/workspace/include/gz/sim/Util.hh:247: warning: The following parameter of gz::sim::resolveSdfWorldFile(const std::string &_sdfFilename, const std::string &_fuelResourceCache="") is not documented:
2026-03-07T23:07:24.7376176Z   parameter '_sdfFilename'
2026-03-07T23:07:24.7377043Z /github/workspace/include/gz/sim/EntityComponentManager.hh:715: warning: The following parameter of gz::sim::EntityComponentManager::ApplyEntityDiff(const EntityComponentManager &_other, const EntityComponentManagerDiff &_diff) is not documented:
2026-03-07T23:07:24.7377934Z   parameter '_diff'
2026-03-07T23:07:24.7378658Z /github/workspace/include/gz/sim/EntityComponentManager.hh:76: warning: argument '_from' of command @param is not found in the argument list of EntityComponentManager::CopyFrom(const EntityComponentManager &_fromEcm)
2026-03-07T23:07:24.7379974Z /github/workspace/include/gz/sim/EntityComponentManager.hh:76: warning: The following parameter of gz::sim::EntityComponentManager::CopyFrom(const EntityComponentManager &_fromEcm) is not documented:
2026-03-07T23:07:24.7380693Z   parameter '_fromEcm'
2026-03-07T23:07:24.7381606Z /github/workspace/include/gz/sim/EntityComponentManager.hh:571: warning: argument '_changes' of command @param is not found in the argument list of EntityComponentManager::UpdatePeriodicChangeCache(std::unordered_map< ComponentTypeId, std::unordered_set< Entity > > &) const
2026-03-07T23:07:24.7382945Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7384190Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7385151Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:43: warning: Unsupported xml/html tag <output_format> found
2026-03-07T23:07:24.7386228Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:45: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7387208Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:47: warning: Unsupported xml/html tag <environment_variable_x> found
2026-03-07T23:07:24.7388142Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:50: warning: Unsupported xml/html tag <environment_variable_y> found
2026-03-07T23:07:24.7389080Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:53: warning: Unsupported xml/html tag <environment_variable_z> found
2026-03-07T23:07:24.7390001Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:56: warning: Unsupported xml/html tag <transform_type> found
2026-03-07T23:07:24.7391219Z /github/workspace/include/gz/sim/System.hh:179: warning: The following parameter of gz::sim::ISystemConfigureParameters::ConfigureParameters(gz::transport::parameters::ParametersRegistry &_registry, EntityComponentManager &_ecm)=0 is not documented:
2026-03-07T23:07:24.7392098Z   parameter '_ecm'
2026-03-07T23:07:24.7392770Z /github/workspace/src/gui/plugins/component_inspector_editor/JointType.hh:38: warning: argument '_surface' of command @param is not found in the argument list of JointType::OnJointType(QString _jointType)
2026-03-07T23:07:24.7393893Z /github/workspace/src/gui/plugins/component_inspector_editor/JointType.hh:38: warning: The following parameter of gz::sim::JointType::OnJointType(QString _jointType) is not documented:
2026-03-07T23:07:24.7394551Z   parameter '_jointType'
2026-03-07T23:07:24.7395214Z /github/workspace/include/gz/sim/Light.hh:214: warning: argument '_bool' of command @param is not found in the argument list of Light::SetCastShadows(EntityComponentManager &_ecm, bool _castShadows)
2026-03-07T23:07:24.7396549Z /github/workspace/include/gz/sim/Light.hh:214: warning: The following parameter of gz::sim::Light::SetCastShadows(EntityComponentManager &_ecm, bool _castShadows) is not documented:
2026-03-07T23:07:24.7397207Z   parameter '_castShadows'
2026-03-07T23:07:24.7397873Z /github/workspace/include/gz/sim/Light.hh:273: warning: argument '_fallOff' of command @param is not found in the argument list of Light::SetSpotFalloff(EntityComponentManager &_ecm, double _falloff)
2026-03-07T23:07:24.7398986Z /github/workspace/include/gz/sim/Light.hh:273: warning: The following parameter of gz::sim::Light::SetSpotFalloff(EntityComponentManager &_ecm, double _falloff) is not documented:
2026-03-07T23:07:24.7399627Z   parameter '_falloff'
2026-03-07T23:07:24.7400308Z /github/workspace/src/gui/plugins/plotting/Plotting.hh:140: warning: argument '_value' of command @param is not found in the argument list of Plotting::SetData(std::string _Id, const sdf::Physics &_physics)
2026-03-07T23:07:24.7401536Z /github/workspace/src/gui/plugins/plotting/Plotting.hh:140: warning: The following parameter of gz::sim::Plotting::SetData(std::string _Id, const sdf::Physics &_physics) is not documented:
2026-03-07T23:07:24.7402195Z   parameter '_physics'
2026-03-07T23:07:24.7402561Z /github/workspace/include/gz/sim/Server.hh:289: warning: Unsupported xml/html tag <plugin> found
2026-03-07T23:07:24.7403125Z /github/workspace/include/gz/sim/Server.hh:249: warning: Unsupported xml/html tag <plugin> found
2026-03-07T23:07:24.7403887Z /github/workspace/include/gz/sim/Server.hh:358: warning: argument 'runnerId' of command @param is not found in the argument list of Server::Reset(const std::size_t _runnerId)
2026-03-07T23:07:24.7404825Z /github/workspace/include/gz/sim/Server.hh:358: warning: The following parameter of gz::sim::Server::Reset(const std::size_t _runnerId) is not documented:
2026-03-07T23:07:24.7405381Z   parameter '_runnerId'
2026-03-07T23:07:24.7406233Z /github/workspace/src/gui/plugins/view_angle/ViewAngle.hh:94: warning: argument '_mode' of command @param is not found in the argument list of ViewAngle::OnViewControl(const QString &_controller)
2026-03-07T23:07:24.7407099Z /github/workspace/include/gz/sim/comms/Broker.hh:66: warning: Unsupported xml/html tag <broker> found
2026-03-07T23:07:24.7407745Z /github/workspace/include/gz/sim/comms/Broker.hh:68: warning: Unsupported xml/html tag <messages_topic> found
2026-03-07T23:07:24.7408384Z /github/workspace/include/gz/sim/comms/Broker.hh:70: warning: Unsupported xml/html tag <bind_service> found
2026-03-07T23:07:24.7409014Z /github/workspace/include/gz/sim/comms/Broker.hh:72: warning: Unsupported xml/html tag <unbind_service> found
2026-03-07T23:07:24.7409620Z /github/workspace/include/gz/sim/comms/Broker.hh:78: warning: Unsupported xml/html tag <plugin> found
2026-03-07T23:07:24.7410222Z /github/workspace/include/gz/sim/comms/Broker.hh:79: warning: Unsupported xml/html tag <broker> found
2026-03-07T23:07:24.7410835Z /github/workspace/include/gz/sim/comms/Broker.hh:80: warning: Unsupported xml/html tag <messages_topic> found
2026-03-07T23:07:24.7411466Z /github/workspace/include/gz/sim/comms/Broker.hh:80: warning: Unsupported xml/html tag </messages_topic> found
2026-03-07T23:07:24.7412092Z /github/workspace/include/gz/sim/comms/Broker.hh:81: warning: Unsupported xml/html tag <bind_service> found
2026-03-07T23:07:24.7412699Z /github/workspace/include/gz/sim/comms/Broker.hh:81: warning: Unsupported xml/html tag </bind_service> found
2026-03-07T23:07:24.7413325Z /github/workspace/include/gz/sim/comms/Broker.hh:82: warning: Unsupported xml/html tag <unbind_service> found
2026-03-07T23:07:24.7413964Z /github/workspace/include/gz/sim/comms/Broker.hh:82: warning: Unsupported xml/html tag </unbind_service> found
2026-03-07T23:07:24.7414580Z /github/workspace/include/gz/sim/comms/Broker.hh:83: warning: Unsupported xml/html tag </broker> found
2026-03-07T23:07:24.7415176Z /github/workspace/include/gz/sim/comms/Broker.hh:84: warning: Unsupported xml/html tag </plugin> found
2026-03-07T23:07:24.7415932Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:50: warning: Unsupported xml/html tag <step_size> found
2026-03-07T23:07:24.7416576Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:52: warning: Unsupported xml/html tag <step_size> found
2026-03-07T23:07:24.7417205Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:58: warning: Unsupported xml/html tag <physics> found
2026-03-07T23:07:24.7417862Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:59: warning: Unsupported xml/html tag <max_step_size> found
2026-03-07T23:07:24.7418540Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:59: warning: Unsupported xml/html tag </max_step_size> found
2026-03-07T23:07:24.7419217Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:60: warning: Unsupported xml/html tag <real_time_factor> found
2026-03-07T23:07:24.7419943Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:60: warning: Unsupported xml/html tag </real_time_factor> found
2026-03-07T23:07:24.7420623Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:61: warning: Unsupported xml/html tag </physics> found
2026-03-07T23:07:24.7421259Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:64: warning: Unsupported xml/html tag <plugin> found
2026-03-07T23:07:24.7421889Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:65: warning: Unsupported xml/html tag <step_size> found
2026-03-07T23:07:24.7422516Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:65: warning: Unsupported xml/html tag </step_size> found
2026-03-07T23:07:24.7423141Z /github/workspace/include/gz/sim/comms/ICommsModel.hh:66: warning: Unsupported xml/html tag </plugin> found
2026-03-07T23:07:24.7424142Z /github/workspace/include/gz/sim/comms/MsgManager.hh:112: warning: argument '_Msg' of command @param is not found in the argument list of MsgManager::RemoveInbound(const std::string &_address, const msgs::DataframeSharedPtr &_msg)
2026-03-07T23:07:24.7425519Z /github/workspace/include/gz/sim/comms/MsgManager.hh:112: warning: The following parameter of gz::sim::comms::MsgManager::RemoveInbound(const std::string &_address, const msgs::DataframeSharedPtr &_msg) is not documented:
2026-03-07T23:07:24.7426409Z   parameter '_msg'
2026-03-07T23:07:24.7427138Z /github/workspace/include/gz/sim/components/Factory.hh:95: warning: argument '_ptr' of command @param is not found in the argument list of RegistrationObjectId::RegistrationObjectId(std::uintptr_t _ptrAddress)
2026-03-07T23:07:24.7428574Z /github/workspace/include/gz/sim/components/Factory.hh:95: warning: The following parameter of gz::sim::components::RegistrationObjectId::RegistrationObjectId(std::uintptr_t _ptrAddress) is not documented:
2026-03-07T23:07:24.7429310Z   parameter '_ptrAddress'
2026-03-07T23:07:24.7430368Z /github/workspace/include/gz/sim/gui/Gui.hh:51: warning: argument '_renderEngineGuiApiBackend' of command @param is not found in the argument list of gz::sim::gui::runGui(int &_argc, char **_argv, const char *_guiConfig, const char *_sdfFile, int _waitGui, const char *_renderEngine=nullptr, const char *_renderEngineApiBackend=nullptr)
2026-03-07T23:07:24.7432144Z /github/workspace/include/gz/sim/gui/Gui.hh:51: warning: The following parameter of gz::sim::gui::runGui(int &_argc, char **_argv, const char *_guiConfig, const char *_sdfFile, int _waitGui, const char *_renderEngine=nullptr, const char *_renderEngineApiBackend=nullptr) is not documented:
2026-03-07T23:07:24.7433110Z   parameter '_renderEngineApiBackend'
2026-03-07T23:07:24.7434416Z /github/workspace/src/systems/environment_preload/VisualizationTool.hh:85: warning: argument '_xSample' of command @param is not found in the argument list of EnvironmentVisualizationTool::Step(const UpdateInfo &_info, const EntityComponentManager &_ecm, const std::shared_ptr< components::EnvironmentalData > &_data, unsigned int _xSamples, unsigned int _ySamples, unsigned int _zSamples)
2026-03-07T23:07:24.7437022Z /github/workspace/src/systems/environment_preload/VisualizationTool.hh:85: warning: argument '_ySample' of command @param is not found in the argument list of EnvironmentVisualizationTool::Step(const UpdateInfo &_info, const EntityComponentManager &_ecm, const std::shared_ptr< components::EnvironmentalData > &_data, unsigned int _xSamples, unsigned int _ySamples, unsigned int _zSamples)
2026-03-07T23:07:24.7439550Z /github/workspace/src/systems/environment_preload/VisualizationTool.hh:85: warning: argument '_zSample' of command @param is not found in the argument list of EnvironmentVisualizationTool::Step(const UpdateInfo &_info, const EntityComponentManager &_ecm, const std::shared_ptr< components::EnvironmentalData > &_data, unsigned int _xSamples, unsigned int _ySamples, unsigned int _zSamples)
2026-03-07T23:07:24.7442380Z /github/workspace/src/systems/environment_preload/VisualizationTool.hh:85: warning: The following parameters of gz::sim::GZ_SIM_VERSION_NAMESPACE::EnvironmentVisualizationTool::Step(const UpdateInfo &_info, const EntityComponentManager &_ecm, const std::shared_ptr< components::EnvironmentalData > &_data, unsigned int _xSamples, unsigned int _ySamples, unsigned int _zSamples) are not documented:
2026-03-07T23:07:24.7443705Z   parameter '_xSamples'
2026-03-07T23:07:24.7443899Z   parameter '_ySamples'
2026-03-07T23:07:24.7444086Z   parameter '_zSamples'
2026-03-07T23:07:24.7444530Z /github/workspace/src/gui/plugins/visualize_lidar/VisualizeLidar.hh:83: warning: expected whitespace after \param command
2026-03-07T23:07:24.7445254Z /github/workspace/src/systems/entity_semantics/EntitySemantics.hh:50: warning: Unsupported xml/html tag <model> found
2026-03-07T23:07:24.7446430Z /github/workspace/include/gz/sim/components/Model.hh:40: warning: argument '_time' of command @param is not found in the argument list of SdfModelSerializer::Serialize(std::ostream &_out, const sdf::Model &_model)
2026-03-07T23:07:24.7447676Z /github/workspace/include/gz/sim/components/Model.hh:40: warning: The following parameter of gz::sim::serializers::SdfModelSerializer::Serialize(std::ostream &_out, const sdf::Model &_model) is not documented:
2026-03-07T23:07:24.7448456Z   parameter '_model'
2026-03-07T23:07:24.7448869Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:52: warning: Unsupported xml/html tag <max_range> found
2026-03-07T23:07:24.7449619Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:54: warning: Unsupported xml/html tag <speed_of_sound> found
2026-03-07T23:07:24.7450380Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:56: warning: Unsupported xml/html tag <collision_time_per_byte> found
2026-03-07T23:07:24.7451158Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:61: warning: Unsupported xml/html tag <collision_time_packet_drop> found
2026-03-07T23:07:24.7451934Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:65: warning: Unsupported xml/html tag <propagation_model> found
2026-03-07T23:07:24.7452670Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:67: warning: Unsupported xml/html tag <source_power> found
2026-03-07T23:07:24.7453373Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:69: warning: Unsupported xml/html tag <noise_level> found
2026-03-07T23:07:24.7454103Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:72: warning: Unsupported xml/html tag <spectral_efficiency> found
2026-03-07T23:07:24.7454813Z /github/workspace/src/systems/acoustic_comms/AcousticComms.hh:76: warning: Unsupported xml/html tag <seed> found
2026-03-07T23:07:24.7455517Z /github/workspace/src/systems/apply_link_wrench/ApplyLinkWrench.hh:46: warning: Unsupported xml/html tag <world_name> found
2026-03-07T23:07:24.7456375Z /github/workspace/src/systems/apply_link_wrench/ApplyLinkWrench.hh:50: warning: Unsupported xml/html tag <world_name> found
2026-03-07T23:07:24.7457089Z /github/workspace/src/systems/apply_link_wrench/ApplyLinkWrench.hh:56: warning: Unsupported xml/html tag <world_name> found
2026-03-07T23:07:24.7457853Z /github/workspace/src/systems/camera_video_recorder/CameraVideoRecorder.hh:44: warning: Unsupported xml/html tag <model_name> found
2026-03-07T23:07:24.7458629Z /github/workspace/src/systems/camera_video_recorder/CameraVideoRecorder.hh:44: warning: Unsupported xml/html tag <link_name> found
2026-03-07T23:07:24.7459416Z /github/workspace/src/systems/camera_video_recorder/CameraVideoRecorder.hh:45: warning: Unsupported xml/html tag <sensor_name> found
2026-03-07T23:07:24.7460183Z /github/workspace/src/systems/detachable_joint/DetachableJoint.hh:54: warning: Unsupported xml/html tag <detach_topic> found
2026-03-07T23:07:24.7460933Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:41: warning: Unsupported xml/html tag <lidar_topic> found
2026-03-07T23:07:24.7461691Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:42: warning: Unsupported xml/html tag <width> found
2026-03-07T23:07:24.7462418Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:43: warning: Unsupported xml/html tag <height> found
2026-03-07T23:07:24.7463270Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:44: warning: Unsupported xml/html tag <resolution> found
2026-03-07T23:07:24.7464026Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:45: warning: Unsupported xml/html tag <sensor_link> found
2026-03-07T23:07:24.7464791Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:47: warning: Unsupported xml/html tag <image_topic> found
2026-03-07T23:07:24.7465542Z /github/workspace/src/systems/free_space_explorer/FreeSpaceExplorer.hh:48: warning: Unsupported xml/html tag <start_topic> found
2026-03-07T23:07:24.7466373Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:85: warning: Unsupported xml/html tag <xDotU> found
2026-03-07T23:07:24.7467057Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:86: warning: Unsupported xml/html tag <yDotV> found
2026-03-07T23:07:24.7476212Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:87: warning: Unsupported xml/html tag <zDotW> found
2026-03-07T23:07:24.7477361Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:88: warning: Unsupported xml/html tag <kDotP> found
2026-03-07T23:07:24.7478261Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:89: warning: Unsupported xml/html tag <mDotQ> found
2026-03-07T23:07:24.7479097Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:90: warning: Unsupported xml/html tag <nDotR> found
2026-03-07T23:07:24.7479773Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:91: warning: Unsupported xml/html tag <xUabsU> found
2026-03-07T23:07:24.7480455Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:92: warning: Unsupported xml/html tag <xU> found
2026-03-07T23:07:24.7481155Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:93: warning: Unsupported xml/html tag <yVabsV> found
2026-03-07T23:07:24.7481838Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:94: warning: Unsupported xml/html tag <yV> found
2026-03-07T23:07:24.7482520Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:95: warning: Unsupported xml/html tag <zWabsW> found
2026-03-07T23:07:24.7483181Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:96: warning: Unsupported xml/html tag <zW> found
2026-03-07T23:07:24.7483848Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:97: warning: Unsupported xml/html tag <kPabsP> found
2026-03-07T23:07:24.7484513Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:98: warning: Unsupported xml/html tag <kP> found
2026-03-07T23:07:24.7485182Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:99: warning: Unsupported xml/html tag <mQabsQ> found
2026-03-07T23:07:24.7486075Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:100: warning: Unsupported xml/html tag <mQ> found
2026-03-07T23:07:24.7486745Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:101: warning: Unsupported xml/html tag <nRabsR> found
2026-03-07T23:07:24.7487445Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:102: warning: Unsupported xml/html tag <nR> found
2026-03-07T23:07:24.7488119Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:111: warning: Unsupported xml/html tag <xDotR> found
2026-03-07T23:07:24.7488804Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:117: warning: Unsupported xml/html tag <xRabsQ> found
2026-03-07T23:07:24.7489501Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:121: warning: Unsupported xml/html tag <xRQ> found
2026-03-07T23:07:24.7490161Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:123: warning: Unsupported xml/html tag <xR> found
2026-03-07T23:07:24.7490861Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:126: warning: Unsupported xml/html tag <water_density> found
2026-03-07T23:07:24.7491583Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:128: warning: Unsupported xml/html tag <link_name> found
2026-03-07T23:07:24.7492333Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:130: warning: Unsupported xml/html tag <namespace> found
2026-03-07T23:07:24.7493094Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:136: warning: Unsupported xml/html tag <default_current> found
2026-03-07T23:07:24.7493839Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:138: warning: Unsupported xml/html tag <disable_coriolis> found
2026-03-07T23:07:24.7494584Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:139: warning: Unsupported xml/html tag <disable_added_mass> found
2026-03-07T23:07:24.7495317Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:146: warning: Unsupported xml/html tag <lookup_current_x> found
2026-03-07T23:07:24.7496179Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:147: warning: Unsupported xml/html tag <lookup_current_y> found
2026-03-07T23:07:24.7496909Z /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:148: warning: Unsupported xml/html tag <lookup_current_z> found
2026-03-07T23:07:24.7498227Z /github/workspace/src/systems/elevator/utils/JointMonitor.hh:54: warning: argument '_jointTarget' of command @param is not found in the argument list of JointMonitor::Configure(Entity _joint, double _target, double _posEps, double _velEps, const std::function< void()> &_jointTargetReachedCallback)
2026-03-07T23:07:24.7500000Z /github/workspace/src/systems/elevator/utils/JointMonitor.hh:54: warning: The following parameter of gz::sim::systems::JointMonitor::Configure(Entity _joint, double _target, double _posEps, double _velEps, const std::function< void()> &_jointTargetReachedCallback) is not documented:
2026-03-07T23:07:24.7500947Z   parameter '_target'
2026-03-07T23:07:24.7501816Z /github/workspace/include/gz/sim/System.hh:179: warning: The following parameter of gz::sim::systems::JointPositionController::ConfigureParameters(gz::transport::parameters::ParametersRegistry &_registry, EntityComponentManager &_ecm) is not documented:
2026-03-07T23:07:24.7502700Z   parameter '_ecm'
2026-03-07T23:07:24.7503148Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:42: warning: Unsupported xml/html tag <slip_map> found
2026-03-07T23:07:24.7503866Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:60: warning: Unsupported xml/html tag <size_x> found
2026-03-07T23:07:24.7504575Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:61: warning: Unsupported xml/html tag <size_y> found
2026-03-07T23:07:24.7505308Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:62: warning: Unsupported xml/html tag <wheel_link_name> found
2026-03-07T23:07:24.7506218Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:63: warning: Unsupported xml/html tag <wheel_link_name> found
2026-03-07T23:07:24.7507008Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:64: warning: Unsupported xml/html tag <slip_compliance_lateral_delta> found
2026-03-07T23:07:24.7507866Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:66: warning: Unsupported xml/html tag <slip_compliance_longitudinal_delta> found
2026-03-07T23:07:24.7508690Z /github/workspace/src/systems/lookup_wheel_slip/LookupWheelSlip.hh:68: warning: Unsupported xml/html tag <friction_delta> found
2026-03-07T23:07:24.7509472Z /github/workspace/src/systems/model_photo_shoot/ModelPhotoShoot.hh:68: warning: Unsupported xml/html tag <translation_data_file> found
2026-03-07T23:07:24.7510251Z /github/workspace/src/systems/model_photo_shoot/ModelPhotoShoot.hh:70: warning: Unsupported xml/html tag <random_joints_pose> found
2026-03-07T23:07:24.7511062Z /github/workspace/src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh:64: warning: Unsupported xml/html tag <visualize_forces> found
2026-03-07T23:07:24.7511780Z /github/workspace/src/systems/sensors/Sensors.hh:45: warning: Unsupported xml/html tag <scene> found
2026-03-07T23:07:24.7512360Z /github/workspace/src/systems/sensors/Sensors.hh:48: warning: Unsupported xml/html tag <scene> found
2026-03-07T23:07:24.7512982Z /github/workspace/src/systems/sensors/Sensors.hh:54: warning: Found unknown command '\TODO'
2026-03-07T23:07:24.7513615Z /github/workspace/src/systems/touch_plugin/TouchPlugin.hh:55: warning: Unsupported xml/html tag <collision> found
2026-03-07T23:07:24.7514281Z /github/workspace/src/systems/touch_plugin/TouchPlugin.hh:59: warning: Unsupported xml/html tag <collision> found
2026-03-07T23:07:24.7515000Z /github/workspace/src/systems/trajectory_follower/TrajectoryFollower.hh:44: warning: Unsupported xml/html tag <waypoints> found
2026-03-07T23:07:24.7515857Z /github/workspace/src/systems/trajectory_follower/TrajectoryFollower.hh:45: warning: Unsupported xml/html tag <line> found
2026-03-07T23:07:24.7516610Z /github/workspace/src/systems/trajectory_follower/TrajectoryFollower.hh:46: warning: Unsupported xml/html tag <circle> found
2026-03-07T23:07:24.7517352Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:87: warning: Unsupported xml/html tag <publication_hz> found
2026-03-07T23:07:24.7518123Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:90: warning: Unsupported xml/html tag <port> found
2026-03-07T23:07:24.7518863Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:92: warning: Unsupported xml/html tag <authorization_key> found
2026-03-07T23:07:24.7519677Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:94: warning: Unsupported xml/html tag <admin_authorization_key> found
2026-03-07T23:07:24.7520501Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:97: warning: Unsupported xml/html tag <admin_authorization_key> found
2026-03-07T23:07:24.7521283Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:99: warning: Unsupported xml/html tag <authorization_key> found
2026-03-07T23:07:24.7522035Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:102: warning: Unsupported xml/html tag <max_connections> found
2026-03-07T23:07:24.7522773Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:109: warning: Unsupported xml/html tag <ssl> found
2026-03-07T23:07:24.7523483Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:119: warning: Unsupported xml/html tag <cert_file> found
2026-03-07T23:07:24.7524204Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:119: warning: Unsupported xml/html tag <ssl> found
2026-03-07T23:07:24.7524935Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:121: warning: Unsupported xml/html tag <private_key_file> found
2026-03-07T23:07:24.7525770Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:121: warning: Unsupported xml/html tag <ssl> found
2026-03-07T23:07:24.7526514Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:192: warning: Unsupported xml/html tag <plugin> found
2026-03-07T23:07:24.7527240Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:195: warning: Unsupported xml/html tag <publication_hz> found
2026-03-07T23:07:24.7528004Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:195: warning: Unsupported xml/html tag </publication_hz> found
2026-03-07T23:07:24.7528903Z /github/workspace/src/systems/websocket_server/WebsocketServer.hh:196: warning: Unsupported xml/html tag </plugin> found
2026-03-07T23:07:24.7529974Z /github/workspace/include/gz/sim/System.hh:179: warning: The following parameter of gz::sim::systems::WheelSlip::ConfigureParameters(gz::transport::parameters::ParametersRegistry &_registry, EntityComponentManager &_ecm) is not documented:
2026-03-07T23:07:24.7530816Z   parameter '_ecm'
2026-03-07T23:07:24.7531554Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:82: warning: argument '_event' of command @param is not found in the argument list of CabinAtTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7532872Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:82: warning: argument '_source' of command @param is not found in the argument list of CabinAtTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7534264Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:82: warning: argument '_target' of command @param is not found in the argument list of CabinAtTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7535730Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:42: warning: argument '_source' of command @param is not found in the argument list of EnqueueNewTarget< trigger >::operator()(const Event &_event, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7537168Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:42: warning: argument '_target' of command @param is not found in the argument list of EnqueueNewTarget< trigger >::operator()(const Event &_event, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7538522Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:62: warning: argument '_event' of command @param is not found in the argument list of NewTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7539856Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:62: warning: argument '_source' of command @param is not found in the argument list of NewTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7541152Z /github/workspace/src/systems/elevator/state_machine/ActionsImpl.hh:62: warning: argument '_target' of command @param is not found in the argument list of NewTarget::operator()(const Event &, Fsm &_fsm, Source &, Target &)
2026-03-07T23:07:24.7542272Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7543219Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7544155Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7545091Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7546122Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
2026-03-07T23:07:24.7547048Z /github/workspace/src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh:36: warning: Unsupported xml/html tag <environment_variable> found
~~~

</details>

### PR DESCRIPTION
**Pull request by ammaarrahmed**
# 🦟 Bug fix

Fixes #3371

## Summary
This PR fixes Doxygen documentation issues in a small set of headers and maritime tutorials that were contributing to documentation-check failures and incorrect rendered math output.

The main tutorial-side fix is to use Doxygen-compatible display math syntax and correct underscore escaping so MathJax renders identifiers such as `volume_neutral`, `outer_volume`, `main_buoyancy_volume`, `fluid_density`, `thrust_constant`, and `propeller_blade_size` correctly.

#### Core Headers & Systems
* **include/gz/sim/Util.hh**: Fixed a parameter name mismatch where the documentation referenced `_filename_` but the function signature uses `_filename`.
* **include/gz/sim/Conversions.hh**: Removed stale `\param` entries from generic conversion template declarations whose parameters are intentionally unnamed, resolving "argument not found" warnings.
* **src/systems/sensors/Sensors.hh**: Changed `\TODO` to Doxygen-standard lowercase `\todo`.
* **src/gui/plugins/visualize_lidar/VisualizeLidar.hh**: Fixed `\param[in]` formatting by adding the missing space before `_msg`.
* **src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh**: Replaced raw XML/SDF-style tags in the documentation with inline code formatting so Doxygen no longer interprets them as unsupported HTML/XML tags.

#### Tutorials & Math
* **tutorials/theory_buoyancy.md**
* **tutorials/lander.md**
* **tutorials/underwater_vehicles.md**

For these tutorial pages:
* Replaced Markdown display math delimiters `$$ ... $$` with Doxygen-compatible `\f[ ... \f]`.
* Replaced double-escaped underscores (`\\_`) inside math expressions with single-escaped underscores (`\_`) so MathJax no longer treats `\\` as a line break and renders variable names correctly.

## Verification
* Regenerated the edited tutorial pages through Doxygen with MathJax enabled and checked the rendered HTML output for the three modified tutorials.
* Confirmed the previously reported math-rendering issue no longer occurs in the generated pages.
* Confirmed the warning logs no longer contain the targeted warning signatures related to the fixed math and XML-tag formatting issues.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added a screen capture or video to the PR description that demonstrates the fix (as needed)
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] Updated Bazel files (if adding new files). Created an issue otherwise.
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers
- [ ] Was GenAI used to generate this PR? If so, make sure to add "Generated-by" to your commits. (See [this policy](https://osralliance.org/wp-content/uploads/2025/05/OSRF-Policy-on-the-Use-of-Generative-Tools-Generative-AI-in-Contributions.pdf) for more info.)

### CODE REVIEW

**Comment by ammaarrahmed** [comment]
I've just pushed a second commit (a105f10) to this PR. this adds the LaTeX math fixes for the lander/buoyancy tutorials and wraps the XML tags in the Environmental Sensor System to resolve the 'Unsupported tag' warnings.
thanks.

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 1]
```diff
@@ -40,6 +40,7 @@ class EnvironmentalSensorSystemPrivate;
 /// currents.
 ///
 /// Tags:
+/// \code{.xml}
 ///  <output_format> - Either "scalar" or "vector3" depending on type
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<output_format>` - Either "scalar" or "vector3" depending on type
```

these comments contain XML tags, but they aren't actually XML, so I recommend putting backticks around the tags and removing the `\code{.xml}` and `\endcode`

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 2]
```diff
@@ -40,6 +40,7 @@ class EnvironmentalSensorSystemPrivate;
...
 ///    of output data desired.
 ///  <environment_variable> - Only for scalar type. The name of the column of
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<environment_variable>` - Only for scalar type. The name of the column of
```

and so on for the other xml tags

File: tutorials/theory_buoyancy.md [hunk 3]
```diff
@@ -32,7 +32,7 @@ to match your expected center of buoyancy.
 The buoyancy force is proportional to the volume of air in the vehicle according
 to this equation:
 
-$$volume\\_neutral = \frac{mass}{waterDensity}$$
+\f[volume\\_neutral = \frac{mass}{waterDensity}\f]
```
Comment (scpeters) [inline tutorials/theory_buoyancy.md]: several variables are now rendering differently, for example `volume_neutral`: the `_` no longer appearing and the `n` becoming a subscript

compare https://gazebosim.org/api/sim/10/theory_buoyancy.html with this screenshot I made from a rendering of this branch:

Image

**Comment by ammaarrahmed** [comment]
Hey @scpeters thanks a lot for pointing out these things.
1. I have removed the \code{.xml} and \endcode tags and instead used backticks everywhere in EnvironmentalSensorSystem.hh 
2. I carefully reviewed theory_buoyancy.md and I found the mistake i made ,I was using :
```
\f[volume\\_neutral = \frac{mass}{waterDensity}\f]
```
when instead i should have used : 
```
 \f[volume\_neutral = \frac{mass}{waterDensity}\f]
```
**previous formatting caused MathJax to interpret \\ as a newline, pushing subsequent characters into a subscript.**

Screenshots of rendering of variables after fix : 
**theory_buoyancy.md** :
image

**lander.md** : 
image
image

**underwater_vehicles.md** : 
image

I rendered the tutorial pages with Doxygen + MathJax enabled directly , which is the part affected by this PR.

**Comment by ammaarrahmed** [comment]
@scpeters  I think the UBuntu CI/ Ubuntu noble CI (gui disabled ) check is failing because when I added back ticks to EnvironmentalSensorSystem.hh the line must have went over the 80 character limit and tripped the cpplint failure , should I implement a fix by wrapping the lines affected as : 
This goes over the limit : 
```
/// `<environment_variable_x> - The name of the field to be used as the x value
```

This might not  : 
```
/// `<environment_variable_x>` - The name of the field to be used as the x
/// value in global frame for vector3
```
I haven't tested it on my local setup as I'm traveling , so I'll have to verify it first if it fixes the issue using the awk length command. But if you say that I should leave it as it is then I can do that as well.

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 4]
```diff
@@ -33,27 +33,27 @@ class EnvironmentalSensorSystemPrivate;
...
 /// Tags:
-///  <output_format> - Either "scalar" or "vector3" depending on type
+///  `<output_format>` - Either "scalar" or "vector3" depending on type
 ///    of output data desired.
-///  <environment_variable> - Only for scalar type. The name of the column of
+///  `<environment_variable>` - Only for scalar type. The name of the column of
 ///    the CSV file to be used.
-///  <environment_variable_x> - The name of the field to be used as the x value
+///  `<environment_variable_x>` - The name of the field to be used as the x value
 ///    in global frame for vector3 fields. Note: If this is left out and
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<environment_variable_x>` - The name of the field to be used as the x
///    value in global frame for vector3 fields. Note: If this is left out and
```

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 5]
```diff
@@ -33,27 +33,27 @@ class EnvironmentalSensorSystemPrivate;
...
 ///    vector3 is set, then the x value defaults to zero.
-///  <environment_variable_y> - The name of the field to be used as the y value
+///  `<environment_variable_y>` - The name of the field to be used as the y value
 ///    in global frame for vector3 fields. Note: If this is left out and
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<environment_variable_y>` - The name of the field to be used as the y
///    value in global frame for vector3 fields. Note: If this is left out and
```

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 6]
```diff
@@ -33,27 +33,27 @@ class EnvironmentalSensorSystemPrivate;
...
 ///    vector3 is set, then the y value defaults to zero.
-///  <environment_variable_z> - The name of the field to be used as the z value
+///  `<environment_variable_z>` - The name of the field to be used as the z value
 ///    in global frame vector3 fields. Note: If this is left out and
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<environment_variable_z>` - The name of the field to be used as the z
///    value in global frame vector3 fields. Note: If this is left out and
```

File: src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh [hunk 7]
```diff
@@ -33,27 +33,27 @@ class EnvironmentalSensorSystemPrivate;
...
 ///    vector3 is set, then the z value defaults to zero.
-///  <transform_type> - When handling vector2 or vector3 types it may be in our
+///  `<transform_type>` - When handling vector2 or vector3 types it may be in our
 ///    interest to transform them to local coordinate frames. For instance
```
Comment (scpeters) [inline src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh]:
```suggestion
///  `<transform_type>` - When handling vector2 or vector3 types it may be in
///    our interest to transform them to local coordinate frames. For instance
```

**Comment by scpeters** [comment]
> @scpeters I think the UBuntu CI/ Ubuntu noble CI (gui disabled ) check is failing because when I added back ticks to EnvironmentalSensorSystem.hh the line must have went over the 80 character limit and tripped the cpplint failure , should I implement a fix by wrapping the lines affected as : This goes over the limit :
> 
> ```
> /// `<environment_variable_x> - The name of the field to be used as the x value
> ```
> 
> This might not :
> 
> ```
> /// `<environment_variable_x>` - The name of the field to be used as the x
> /// value in global frame for vector3
> ```
> 
> I haven't tested it on my local setup as I'm traveling , so I'll have to verify it first if it fixes the issue using the awk length command. But if you say that I should leave it as it is then I can do that as well.

thanks for noticing; I just made the changes as github suggestions and then accepted them as a batch. If CI is happy then I'll merge

thanks again for the fixes!

**Comment by ammaarrahmed** [comment]
No problem at all , I'm happy to contribute more and I can work on the remaining doxygen warnings as well but if you feel that I can work on any other open issue which you think I'm ready for, then that works too.
Thanks for the opportunity.

**Comment by scpeters** [comment]
https://github.com/Mergifyio backport main

**Comment by scpeters** [comment]
> No problem at all , I'm happy to contribute more and I can work on the remaining doxygen warnings as well but if you feel that I can work on any other open issue which you think I'm ready for, then that works too. Thanks for the opportunity.

Thank you for the contribution!

It would be great if you can help fix more doxygen warnings. Once that issue is resolved, I can help you find another place to contribute.
