### PR TITLE
Fix warning message to show precise jump back in time duration

### LINKED ISSUE #2407: Incorrect warning msg when sim jumps back in time
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? citadel and above

In many of gz-sim's systems `PostUpdate` function, there is this code to print warning msg:

```cpp
  if (_info.dt < std::chrono::steady_clock::duration::zero())
  {
    gzwarn << "Detected jump back in time ["
        << std::chrono::duration_cast<std::chrono::seconds>(_info.dt).count()
        << "s]. System may not work properly." << std::endl;
  }
```

The problem is that ` std::chrono::duration_cast<std::chrono::seconds>(_info.dt).count()` will just produce 0 unless `_info.dt` is larger than 1 sec.

A quick fix is to change all instances of this code to `std::chrono::duration<double>(_info.dt).count()`

### PR DESCRIPTION
**Pull request by AddisonFarley**
# 🦟 Bug fix

Fixes #2407 (Incorrect warning msg when sim jumps back in time)

## Summary
Refactor the following warning message code:
```c++
if (_info.dt < std::chrono::steady_clock::duration::zero())
  {
    gzwarn << "Detected jump back in time ["
        << std::chrono::duration_cast<std::chrono::seconds>(_info.dt).count()
        << "s]. System may not work properly." << std::endl;
  }
```

to:
```c++
if (_info.dt < std::chrono::steady_clock::duration::zero())
{
  gzwarn << "Detected jump back in time ["
         << std::chrono::duration<double>(_info.dt).count()
         << "s]. System may not work properly." << std::endl;
}
```

for the following files:

src/systems/ackermann_steering/AckermannSteering.cc
src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
src/systems/air_pressure/AirPressure.cc
src/systems/air_speed/AirSpeed.cc
src/systems/altimeter/Altimeter.cc
src/systems/apply_joint_force/ApplyJointForce.cc
src/systems/battery_plugin/LinearBatteryPlugin.cc
src/systems/contact/Contact.cc
src/systems/diff_drive/DiffDrive.cc
src/systems/force_torque/ForceTorque.cc
src/systems/imu/Imu.cc
src/systems/joint_controller/JointController.cc
src/systems/joint_position_controller/JointPositionController.cc
src/systems/lift_drag/LiftDrag.cc
src/systems/log/LogRecord.cc
src/systems/logical_camera/LogicalCamera.cc
src/systems/magnetometer/Magnetometer.cc
src/systems/mecanum_drive/MecanumDrive.cc
src/systems/multicopter_control/MulticopterVelocityControl.cc
src/systems/multicopter_motor_model/MulticopterMotorModel.cc
src/systems/navsat/NavSat.cc
src/systems/odometry_publisher/OdometryPublisher.cc
src/systems/pose_publisher/PosePublisher.cc
src/systems/touch_plugin/TouchPlugin.cc
src/systems/tracked_vehicle/TrackedVehicle.cc
src/systems/velocity_control/VelocityControl.cc
src/systems/wind_effects/WindEffects.cc

### CODE REVIEW

File: src/systems/ackermann_steering/AckermannSteering.cc [hunk 1]
```diff
@@ -505,12 +505,14 @@ void AckermannSteering::PreUpdate(const UpdateInfo &_info,
...
 
   // \TODO(anyone) Support rewind
-  if (_info.dt < std::chrono::steady_clock::duration::zero())
-  {
-    gzwarn << "Detected jump back in time ["
-        << std::chrono::duration_cast<std::chrono::seconds>(_info.dt).count()
-        << "s]. System may not work properly." << std::endl;
-  }
+  
+if (_info.dt < std::chrono::steady_clock::duration::zero())
```
Comment (iche033) [inline src/systems/ackermann_steering/AckermannSteering.cc:509]: can you update the indentation to match what it was before (2 spaces)?

Comment (AddisonFarley) [reply src/systems/ackermann_steering/AckermannSteering.cc]: Fixed.

**Review by iche033 — APPROVED** [review]
great, thanks for your contribution!
