### PR TITLE
Fix for sensor pointer null when navsat plugin in included in sdf

### LINKED ISSUE #2163: [GUI] [Err] [Conversions.cc:1198] Attempting to convert a NavSat SDF sensor, but the sensor pointer is null.
Ubuntu 22.04, ROS2 Humble, Gazebo Fortress. Installed everything from `apt` repos

I have a differential drive robot on to which I have added a [`navsat` sensor](https://github.com/ashBabu/skidy/blob/ros2-ignition-gazebo/skidy_description/urdf/robot_test_diff_drive.urdf#L155). I launch the simulation with `ros2 launch skidy_bringup bringup_sim.launch.py`. As soon as press the play button in gazebo, the following error comes up although I am able to see the msg being published at the topic that I specified.

`[GUI] [Err] [Conversions.cc:1198] Attempting to convert a NavSat SDF sensor, but the sensor pointer is null.`

### PR DESCRIPTION
**Pull request by ashBabu**
# 🦟 Bug fix

Fixes #2163

## Summary
When the play button is pressed in Gazebo, the terminal window shows an error as described in #2163. 

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

## Test it
* create a `model.sdf ` with the following `navsat` plugin
```
<sensor name="navsat" type="navsat">
   <navsat>
        ....
   </navsat>
   <plugin  filename="libignition-gazebo-navsat-system"  
            name="ignition::gazebo::systems::NavSat">
   </plugin>
</sensor>
```
* `ign gazebo model.sdf`
* Press the play button
* There wont be any error on the terminal

### CODE REVIEW

File: src/Conversions.cc [hunk 1]
```diff
@@ -1424,6 +1424,38 @@ sdf::Sensor gazebo::convert(const msgs::Sensor &_in)
 
     out.SetCameraSensor(sensor);
   }
+
```
Comment (mjcarroll) [inline src/Conversions.cc:1427]: Nit: unnecessary whitespace

File: src/Conversions.cc [hunk 2]
```diff
@@ -1424,6 +1424,38 @@ sdf::Sensor gazebo::convert(const msgs::Sensor &_in)
...
+          }
+      }
+      else
+      {
+          ignerr << "Attempting to convert an navsat sensor message, but the "
+                 << "message does not have a navsat nested message.\n";
+      }
+      out.SetNavSatSensor(sensor);
+  }
+
```
Comment (mjcarroll) [inline src/Conversions.cc:1458]: Nit: unnecessary whitespace

File: src/Conversions.cc [hunk 3]
```diff
@@ -1424,6 +1424,38 @@ sdf::Sensor gazebo::convert(const msgs::Sensor &_in)
...
+  else if (out.Type() == sdf::SensorType::GPS ||
+           out.Type() == sdf::SensorType::NAVSAT)
+  {
+      sdf::NavSat sensor;
+      if (_in.has_gps())
+      {
+          if (_in.gps().position().has_horizontal_noise())
+          {
+              sensor.SetHorizontalPositionNoise(gazebo::convert<sdf::Noise>(_in.gps().position().horizontal_noise()));
```
Comment (mjcarroll) [inline src/Conversions.cc:1436]: Wrap these lines (and the ones below) to 80 char, please

**Review by mjcarroll — COMMENTED** [review]
Minor formatting issues.

Can you also update the title of the PR?

File: src/Conversions.cc (hunk 1 above)
Comment (ashBabu) [reply src/Conversions.cc]: done

File: src/Conversions.cc (hunk 2 above)
Comment (ashBabu) [reply src/Conversions.cc]: done

File: src/Conversions.cc (hunk 3 above)
Comment (ashBabu) [reply src/Conversions.cc]: done

**Comment by ashBabu** [comment]
> Minor formatting issues.
> 
> Can you also update the title of the PR?

done

**Comment by ashBabu** [comment]
I am not sure why some of the checks were unsuccessful. Is there something that I could do to get this approved? Thanks

**Comment by mjcarroll** [comment]
> I am not sure why some of the checks were unsuccessful.

I'm still seeing the code not wrapped at 80 characters, that may be triggering a lint failure.

I believe the other failures are related to https://github.com/gazebosim/gz-sim/pull/2190, so you won't need to fix them.

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Review by iche033 — COMMENTED** [review]
just a minor typo otherwise looks good to me

**Review by ahcorde — APPROVED** [review]
