### PR TITLE
Fix error resolving gazebo classic material when loading world

### LINKED ISSUE #2488: Worlds in quick start on Harmonic contains ignition plugins and crashes with ambiguous errors
## Environment
* OS Version: 
   22.04
* Source or binary build?
   binary 8.5.0
  
  

## Description

* Expected behavior: When I run worlds on quick start menu, I expect them to run.
* Actual behavior: Exit with errors.

The worlds contains ignition:: plugins, hence why it probably crashes, but it isn't obvious from errors, it might be good idea to print some warning that the worlds contains ignition:: plugins, it's very confusing that first thing people try, results in not so obvious errors.

## Steps to reproduce
1. gz sim --verbose
2. select worlds: Panda, Prius,...
3. crash

## Output

```
Warning [Utils.cc:132] [/sdf/world[@name="sonoma"]/model[@name="prius_hybrid"]/joint[@name="steering_joint"]/axis/use_parent_model_frame:/home/youtube/.gz/fuel/fuel.gazebosim.org/openrobotics/worlds/prius on sonoma raceway/1/sonoma.sdf:L647]: XML Element[use_parent_model_frame], child of element[axis], not defined in SDF. Copying[use_parent_model_frame] as children of [axis].
```

Part of sonoma world:
```
<?xml version="1.0" ?>
<sdf version='1.7'>
  <world name='sonoma'>
    <scene>
      <grid>false</grid>
    </scene>
    <plugin
      filename="ignition-gazebo-physics-system"
      name="ignition::gazebo::systems::Physics">
    </plugin>
    <plugin
      filename="ignition-gazebo-sensors-system"
      name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin
      filename="ignition-gazebo-user-commands-system"
      name="ignition::gazebo::systems::UserCommands">
    </plugin>
    <plugin
      filename="ignition-gazebo-scene-broadcaster-system"
      name="ignition::gazebo::systems::SceneBroadcaster">
    </plugin>
```

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

Fixes #2488

## Summary

Added special handling in SDF find file callback for gazebo classic materials. We currently check for the [hardcoded classic material URI](https://github.com/gazebosim/gz-sim/blob/a2011f30f9873b5247b56c04cceee12a01221d00/src/SdfEntityCreator.cc#L812) in SDFEntityCreator so do not attempt to resolve the material script URI when loading the world. 

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: test/integration/material.cc [hunk 1]
```diff
@@ -296,3 +296,30 @@ TEST_F(MaterialTest, InvalidColor)
   EXPECT_EQ(math::Color(0.0f, 0.0f, 0.0f, 1.0f),
             boxVisualComp->Data().Specular());
 }
+
+TEST_F(MaterialTest, WorldWithClassicMaterial)
+{
+  ServerConfig serverConfig;
+  serverConfig.SetSdfFile(common::joinPaths(PROJECT_SOURCE_PATH,
+      "test/worlds/classic_material.sdf"));
```
Comment (ahcorde) [inline test/integration/material.cc:304]: `gz::common::joinPath()`

Comment (iche033) [reply test/integration/material.cc]: done. [b403f01](https://github.com/gazebosim/gz-sim/pull/2492/commits/b403f01cf784bf555b10657660d1d5ea7d3b3bab)

**Review by azeey — APPROVED** [review]
